// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module FloatToFixed32(	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:46:7
  input  [31:0] io_in,	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:49:14
  output [31:0] io_out	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:49:14
);

  wire [7:0]   _shiftamt_T = io_in[30:23] - 8'h7F;	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:54:25, :56:23
  wire [38:0]  _data_T_9 = {11'h1, io_in[22:0], 5'h0} >> 8'h0 - _shiftamt_T;	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:53:{42,50}, :56:23, :59:{40,48,52}
  wire [293:0] _data_T_14 = {266'h1, io_in[22:0], 5'h0} << _shiftamt_T;	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:53:50, :56:23, :59:40, :60:48
  wire [31:0]  data = _shiftamt_T[7] ? _data_T_9[31:0] : _data_T_14[31:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:56:23, :58:{17,26}, :59:48, :60:48
  assign io_out = io_in[31] ? 32'h0 - data : data;	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:46:7, :55:26, :58:17, :59:52, :61:{16,40}
endmodule

module CLZ32(	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:146:7
  input  [31:0] io_in,	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:147:14
  output [5:0]  io_out	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:147:14
);

  wire [14:0] bx = (|(io_in[31:16])) ? io_in[31:17] : io_in[15:1];	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:147:14, :155:{15,20,37,49}
  wire [6:0]  cx = (|(bx[14:7])) ? bx[14:8] : bx[6:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:155:15, :156:{15,20,37,49}
  wire [2:0]  dx = (|(cx[6:3])) ? cx[6:4] : cx[2:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:156:15, :157:{15,20,37,49}
  assign io_out =
    io_in == 32'h0
      ? 6'h20
      : {1'h0,
         ~(|(io_in[31:16])),
         ~(|(bx[14:7])),
         ~(|(cx[6:3])),
         ~(|(dx[2:1])),
         ~((|(dx[2:1])) ? dx[2] : dx[0])};	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:146:7, :155:{15,20,37}, :156:{15,20,37}, :157:{15,20,37}, :158:{15,20,37,49}, :161:{37,71,105}, :162:{27,61}, :164:{16,23}
endmodule

module FixedToFloat32(	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:269:7
  input  [31:0] io_in,	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:272:14
  output [31:0] io_out	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:272:14
);

  wire [5:0]      _clz32_io_out;	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:285:21
  wire [31:0]     data = io_in[31] ? ~io_in + 32'h1 : io_in;	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:282:{14,20,35,50}
  wire [524318:0] _frac_T_3 =
    {{524287{data[31]}}, data} << {14'h0, _clz32_io_out[4:0]} + 19'h1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:282:14, :285:21, :288:{32,47}, :291:{26,43}
  CLZ32 clz32 (	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:285:21
    .io_in  (data),	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:282:14
    .io_out (_clz32_io_out)
  );
  assign io_out = {io_in[31], 8'h3 - {3'h0, _clz32_io_out[4:0]} + 8'h7F, _frac_T_3[31:9]};	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:269:7, :282:20, :285:21, :288:47, :290:{23,46}, :291:{8,26}, :293:37
endmodule

module VCORDIC(	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
  input         clock,	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
                reset,	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
  input  [31:0] io_in_y0,	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14
  output [31:0] io_out_z	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14
);

  wire [31:0] _tofixedz0_io_out;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:297:28
  wire [31:0] _tofixedy0_io_out;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:296:28
  wire [31:0] _tofixedx0_io_out;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:295:28
  reg  [31:0] xr_0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_10;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_11;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_13;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_14;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] xr_16;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [31:0] yr_0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_10;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_11;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_13;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_14;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] yr_16;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [31:0] zr_0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_10;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_11;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_13;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_14;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [31:0] zr_16;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  always @(posedge clock) begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
    if (reset) begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
      xr_0 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_1 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_2 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_3 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_4 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_5 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_6 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_7 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_8 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_9 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_10 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_11 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_12 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_13 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_14 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_15 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      xr_16 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28
      yr_0 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_1 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_2 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_3 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_4 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_5 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_6 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_7 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_8 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_9 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_10 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_11 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_12 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_13 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_14 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_15 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      yr_16 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28
      zr_0 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_1 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_2 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_3 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_4 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_5 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_6 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_7 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_8 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_9 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_10 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_11 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_12 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_13 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_14 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_15 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
      zr_16 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :297:28
    end
    else begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
      automatic logic        cond;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _x_1_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:32
      automatic logic [31:0] _y_1_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:598:32
      automatic logic        cond_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _xterm_T_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      automatic logic [30:0] xterm_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:603:26
      automatic logic [31:0] _yterm_T_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [30:0] yterm_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:604:26
      automatic logic        cond_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _xterm_T_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33
      automatic logic [29:0] xterm_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:26
      automatic logic [31:0] _yterm_T_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :594:33
      automatic logic [29:0] yterm_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:594:26
      automatic logic [31:0] _x_3_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:85:19, :597:{32,41}
      automatic logic [31:0] _y_3_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:85:19, :598:{32,41}
      automatic logic        cond_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _xterm_T_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      automatic logic [28:0] xterm_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:603:26
      automatic logic [31:0] _yterm_T_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [28:0] yterm_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:604:26
      automatic logic        cond_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _xterm_T_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33
      automatic logic [27:0] xterm_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:26
      automatic logic [31:0] _yterm_T_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :594:33
      automatic logic [27:0] yterm_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:594:26
      automatic logic [31:0] _x_5_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :597:{32,41}
      automatic logic [31:0] _y_5_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :598:{32,41}
      automatic logic        cond_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _xterm_T_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      automatic logic [26:0] xterm_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:603:26
      automatic logic [31:0] _yterm_T_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [26:0] yterm_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:604:26
      automatic logic        cond_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _xterm_T_18;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33
      automatic logic [25:0] xterm_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:26
      automatic logic [31:0] _yterm_T_18;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :594:33
      automatic logic [25:0] yterm_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:594:26
      automatic logic [31:0] _x_7_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :597:{32,41}
      automatic logic [31:0] _y_7_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :598:{32,41}
      automatic logic        cond_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _xterm_T_21;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      automatic logic [24:0] xterm_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:603:26
      automatic logic [31:0] _yterm_T_21;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [24:0] yterm_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:604:26
      automatic logic        cond_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _xterm_T_24;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33
      automatic logic [23:0] xterm_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:26
      automatic logic [31:0] _yterm_T_24;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :594:33
      automatic logic [23:0] yterm_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:594:26
      automatic logic [31:0] _x_9_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :597:{32,41}
      automatic logic [31:0] _y_9_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :598:{32,41}
      automatic logic        cond_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _xterm_T_27;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      automatic logic [22:0] xterm_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:603:26
      automatic logic [31:0] _yterm_T_27;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [22:0] yterm_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:604:26
      automatic logic        cond_10;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _xterm_T_30;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33
      automatic logic [21:0] xterm_10;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:26
      automatic logic [31:0] _yterm_T_30;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :594:33
      automatic logic [21:0] yterm_10;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:594:26
      automatic logic [31:0] _x_11_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:{32,41}
      automatic logic [31:0] _y_11_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:41, :598:{32,41}
      automatic logic        cond_11;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _xterm_T_33;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      automatic logic [20:0] xterm_11;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:603:26
      automatic logic [31:0] _yterm_T_33;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [20:0] yterm_11;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:604:26
      automatic logic        cond_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _xterm_T_36;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33
      automatic logic [19:0] xterm_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:26
      automatic logic [31:0] _yterm_T_36;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :594:33
      automatic logic [19:0] yterm_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:594:26
      automatic logic [31:0] _x_13_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:{32,41}
      automatic logic [31:0] _y_13_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:41, :598:{32,41}
      automatic logic        cond_13;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _xterm_T_39;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      automatic logic [18:0] xterm_13;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:603:26
      automatic logic [31:0] _yterm_T_39;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [18:0] yterm_13;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:604:26
      automatic logic        cond_14;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _xterm_T_42;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33
      automatic logic [17:0] xterm_14;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:26
      automatic logic [31:0] _yterm_T_42;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :594:33
      automatic logic [17:0] yterm_14;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:594:26
      automatic logic [31:0] _x_15_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:{32,41}
      automatic logic [31:0] _y_15_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:41, :598:{32,41}
      automatic logic        cond_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _xterm_T_45;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      automatic logic [16:0] xterm_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:603:26
      automatic logic [31:0] _yterm_T_45;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [16:0] yterm_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:604:26
      automatic logic        cond_16;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _xterm_T_48;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33
      automatic logic [15:0] xterm_16;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:26
      automatic logic [31:0] _yterm_T_48;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :594:33
      automatic logic [15:0] yterm_16;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:594:26
      automatic logic [31:0] _x_17_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:117:17, :597:{32,41}
      automatic logic [31:0] _y_17_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:117:17, :598:{32,41}
      automatic logic        cond_17;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _xterm_T_51;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      automatic logic [14:0] xterm_17;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:603:26
      automatic logic [31:0] _yterm_T_51;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [14:0] yterm_17;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:604:26
      automatic logic        cond_18;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _xterm_T_54;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33
      automatic logic [13:0] xterm_18;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:26
      automatic logic [31:0] _yterm_T_54;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :594:33
      automatic logic [13:0] yterm_18;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:594:26
      automatic logic [31:0] _x_19_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:{32,41}
      automatic logic [31:0] _y_19_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:41, :598:{32,41}
      automatic logic        cond_19;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _xterm_T_57;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      automatic logic [12:0] xterm_19;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:603:26
      automatic logic [31:0] _yterm_T_57;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [12:0] yterm_19;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:604:26
      automatic logic        cond_20;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _xterm_T_60;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33
      automatic logic [11:0] xterm_20;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:26
      automatic logic [31:0] _yterm_T_60;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :594:33
      automatic logic [11:0] yterm_20;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:594:26
      automatic logic [31:0] _x_21_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:{32,41}
      automatic logic [31:0] _y_21_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:41, :598:{32,41}
      automatic logic        cond_21;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _xterm_T_63;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      automatic logic [10:0] xterm_21;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:603:26
      automatic logic [31:0] _yterm_T_63;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [10:0] yterm_21;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:604:26
      automatic logic        cond_22;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _xterm_T_66;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33
      automatic logic [9:0]  xterm_22;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:26
      automatic logic [31:0] _yterm_T_66;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :594:33
      automatic logic [9:0]  yterm_22;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:594:26
      automatic logic [31:0] _x_23_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:{32,41}
      automatic logic [31:0] _y_23_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:41, :598:{32,41}
      automatic logic        cond_23;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _xterm_T_69;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      automatic logic [8:0]  xterm_23;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:603:26
      automatic logic [31:0] _yterm_T_69;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [8:0]  yterm_23;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:604:26
      automatic logic        cond_24;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _xterm_T_72;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33
      automatic logic [7:0]  xterm_24;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:26
      automatic logic [31:0] _yterm_T_72;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :594:33
      automatic logic [7:0]  yterm_24;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:594:26
      automatic logic [31:0] _x_25_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:{32,41}
      automatic logic [31:0] _y_25_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:41, :598:{32,41}
      automatic logic        cond_25;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _xterm_T_75;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      automatic logic [6:0]  xterm_25;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:603:26
      automatic logic [31:0] _yterm_T_75;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [6:0]  yterm_25;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:604:26
      automatic logic        cond_26;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _xterm_T_78;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33
      automatic logic [5:0]  xterm_26;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:26
      automatic logic [31:0] _yterm_T_78;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :594:33
      automatic logic [5:0]  yterm_26;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:594:26
      automatic logic [31:0] _x_27_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:{32,41}
      automatic logic [31:0] _y_27_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:41, :598:{32,41}
      automatic logic        cond_27;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _xterm_T_81;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      automatic logic [4:0]  xterm_27;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:603:26
      automatic logic [31:0] _yterm_T_81;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [4:0]  yterm_27;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:604:26
      automatic logic        cond_28;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _xterm_T_84;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33
      automatic logic [3:0]  xterm_28;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:26
      automatic logic [31:0] _yterm_T_84;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :594:33
      automatic logic [3:0]  yterm_28;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:594:26
      automatic logic [31:0] _x_29_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:{32,41}
      automatic logic [31:0] _y_29_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:41, :598:{32,41}
      automatic logic        cond_29;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _xterm_T_87;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      automatic logic [2:0]  xterm_29;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:603:26
      automatic logic [31:0] _yterm_T_87;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [2:0]  yterm_29;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:604:26
      automatic logic        cond_30;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:591:31
      automatic logic [31:0] _xterm_T_90;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33
      automatic logic [1:0]  xterm_30;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:26
      automatic logic [31:0] _yterm_T_90;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :594:33
      automatic logic [1:0]  yterm_30;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:594:26
      automatic logic [31:0] _x_31_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:{32,41}
      automatic logic [31:0] _y_31_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:597:41, :598:{32,41}
      automatic logic        cond_31;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:602:31
      automatic logic [31:0] _yterm_T_93;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :604:33
      automatic logic [31:0] _xterm_T_93;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :603:33
      cond = $signed(yr_0) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _x_1_T_1 = xr_0 + (cond ? 32'h0 - yr_0 : yr_0);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :266:19, :297:28, :591:31, :593:33, :594:{26,33}, :597:32
      _y_1_T_1 = yr_0 - (cond ? 32'h0 - xr_0 : xr_0);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :266:19, :297:28, :591:31, :593:{26,33}, :598:32
      cond_1 = $signed(_y_1_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :598:32, :602:31
      _xterm_T_3 = 32'h0 - _x_1_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:32, :603:33
      xterm_1 = cond_1 ? _xterm_T_3[31:1] : _x_1_T_1[31:1];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:32, :602:31, :603:{26,33}
      _yterm_T_3 = 32'h0 - _y_1_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :598:32, :604:33
      yterm_1 = cond_1 ? _yterm_T_3[31:1] : _y_1_T_1[31:1];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :598:32, :602:31, :604:{26,33}
      cond_2 = $signed(yr_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _xterm_T_6 = 32'h0 - xr_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28, :593:33
      xterm_2 = cond_2 ? _xterm_T_6[31:2] : xr_1[31:2];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :591:31, :593:{26,33}
      _yterm_T_6 = 32'h0 - yr_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :593:33, :594:33
      yterm_2 = cond_2 ? _yterm_T_6[31:2] : yr_1[31:2];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :591:31, :593:33, :594:{26,33}
      _x_3_T_1 = {{2{yterm_2[29]}}, yterm_2} + xr_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:85:19, :265:19, :594:26, :597:{32,41}
      _y_3_T_1 = yr_1 - {{2{xterm_2[29]}}, xterm_2};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:85:19, :266:19, :593:26, :598:{32,41}
      cond_3 = $signed(_y_3_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :85:19, :297:28, :598:{32,41}, :602:31
      _xterm_T_9 = 32'h0 - _x_3_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :85:19, :297:28, :593:33, :597:{32,41}, :603:33
      xterm_3 = cond_3 ? _xterm_T_9[31:3] : _x_3_T_1[31:3];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:85:19, :593:33, :597:{32,41}, :602:31, :603:{26,33}
      _yterm_T_9 = 32'h0 - _y_3_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :85:19, :297:28, :593:33, :598:{32,41}, :604:33
      yterm_3 = cond_3 ? _yterm_T_9[31:3] : _y_3_T_1[31:3];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:85:19, :593:33, :598:{32,41}, :602:31, :604:{26,33}
      cond_4 = $signed(yr_2) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _xterm_T_12 = 32'h0 - xr_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28, :593:33
      xterm_4 = cond_4 ? _xterm_T_12[31:4] : xr_2[31:4];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :591:31, :593:{26,33}
      _yterm_T_12 = 32'h0 - yr_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :593:33, :594:33
      yterm_4 = cond_4 ? _yterm_T_12[31:4] : yr_2[31:4];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :591:31, :593:33, :594:{26,33}
      _x_5_T_1 = {{4{yterm_4[27]}}, yterm_4} + xr_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :265:19, :594:26, :597:{32,41}
      _y_5_T_1 = yr_2 - {{4{xterm_4[27]}}, xterm_4};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :266:19, :593:26, :598:{32,41}
      cond_5 = $signed(_y_5_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :119:17, :297:28, :598:{32,41}, :602:31
      _xterm_T_15 = 32'h0 - _x_5_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :119:17, :297:28, :593:33, :597:{32,41}, :603:33
      xterm_5 = cond_5 ? _xterm_T_15[31:5] : _x_5_T_1[31:5];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :593:33, :597:{32,41}, :602:31, :603:{26,33}
      _yterm_T_15 = 32'h0 - _y_5_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :119:17, :297:28, :593:33, :598:{32,41}, :604:33
      yterm_5 = cond_5 ? _yterm_T_15[31:5] : _y_5_T_1[31:5];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :593:33, :598:{32,41}, :602:31, :604:{26,33}
      cond_6 = $signed(yr_3) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _xterm_T_18 = 32'h0 - xr_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28, :593:33
      xterm_6 = cond_6 ? _xterm_T_18[31:6] : xr_3[31:6];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :591:31, :593:{26,33}
      _yterm_T_18 = 32'h0 - yr_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :593:33, :594:33
      yterm_6 = cond_6 ? _yterm_T_18[31:6] : yr_3[31:6];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :591:31, :593:33, :594:{26,33}
      _x_7_T_1 = {{6{yterm_6[25]}}, yterm_6} + xr_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :265:19, :594:26, :597:{32,41}
      _y_7_T_1 = yr_3 - {{6{xterm_6[25]}}, xterm_6};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :266:19, :593:26, :598:{32,41}
      cond_7 = $signed(_y_7_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :83:18, :297:28, :598:{32,41}, :602:31
      _xterm_T_21 = 32'h0 - _x_7_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :83:18, :297:28, :593:33, :597:{32,41}, :603:33
      xterm_7 = cond_7 ? _xterm_T_21[31:7] : _x_7_T_1[31:7];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :593:33, :597:{32,41}, :602:31, :603:{26,33}
      _yterm_T_21 = 32'h0 - _y_7_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :83:18, :297:28, :593:33, :598:{32,41}, :604:33
      yterm_7 = cond_7 ? _yterm_T_21[31:7] : _y_7_T_1[31:7];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :593:33, :598:{32,41}, :602:31, :604:{26,33}
      cond_8 = $signed(yr_4) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _xterm_T_24 = 32'h0 - xr_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28, :593:33
      xterm_8 = cond_8 ? _xterm_T_24[31:8] : xr_4[31:8];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :591:31, :593:{26,33}
      _yterm_T_24 = 32'h0 - yr_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :593:33, :594:33
      yterm_8 = cond_8 ? _yterm_T_24[31:8] : yr_4[31:8];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :591:31, :593:33, :594:{26,33}
      _x_9_T_1 = {{8{yterm_8[23]}}, yterm_8} + xr_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :265:19, :594:26, :597:{32,41}
      _y_9_T_1 = yr_4 - {{8{xterm_8[23]}}, xterm_8};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :266:19, :593:26, :598:{32,41}
      cond_9 = $signed(_y_9_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :118:17, :297:28, :598:{32,41}, :602:31
      _xterm_T_27 = 32'h0 - _x_9_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :118:17, :297:28, :593:33, :597:{32,41}, :603:33
      xterm_9 = cond_9 ? _xterm_T_27[31:9] : _x_9_T_1[31:9];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :593:33, :597:{32,41}, :602:31, :603:{26,33}
      _yterm_T_27 = 32'h0 - _y_9_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :118:17, :297:28, :593:33, :598:{32,41}, :604:33
      yterm_9 = cond_9 ? _yterm_T_27[31:9] : _y_9_T_1[31:9];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :593:33, :598:{32,41}, :602:31, :604:{26,33}
      cond_10 = $signed(yr_5) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _xterm_T_30 = 32'h0 - xr_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28, :593:33
      xterm_10 = cond_10 ? _xterm_T_30[31:10] : xr_5[31:10];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :591:31, :593:{26,33}
      _yterm_T_30 = 32'h0 - yr_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :593:33, :594:33
      yterm_10 = cond_10 ? _yterm_T_30[31:10] : yr_5[31:10];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :591:31, :593:33, :594:{26,33}
      _x_11_T_1 = {{10{yterm_10[21]}}, yterm_10} + xr_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :594:26, :597:{32,41}
      _y_11_T_1 = yr_5 - {{10{xterm_10[21]}}, xterm_10};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :593:26, :597:41, :598:{32,41}
      cond_11 = $signed(_y_11_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :597:41, :598:{32,41}, :602:31
      _xterm_T_33 = 32'h0 - _x_11_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:{32,41}, :603:33
      xterm_11 = cond_11 ? _xterm_T_33[31:11] : _x_11_T_1[31:11];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:{32,41}, :602:31, :603:{26,33}
      _yterm_T_33 = 32'h0 - _y_11_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:41, :598:{32,41}, :604:33
      yterm_11 = cond_11 ? _yterm_T_33[31:11] : _y_11_T_1[31:11];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:41, :598:{32,41}, :602:31, :604:{26,33}
      cond_12 = $signed(yr_6) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _xterm_T_36 = 32'h0 - xr_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28, :593:33
      xterm_12 = cond_12 ? _xterm_T_36[31:12] : xr_6[31:12];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :591:31, :593:{26,33}
      _yterm_T_36 = 32'h0 - yr_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :593:33, :594:33
      yterm_12 = cond_12 ? _yterm_T_36[31:12] : yr_6[31:12];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :591:31, :593:33, :594:{26,33}
      _x_13_T_1 = {{12{yterm_12[19]}}, yterm_12} + xr_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :594:26, :597:{32,41}
      _y_13_T_1 = yr_6 - {{12{xterm_12[19]}}, xterm_12};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :593:26, :597:41, :598:{32,41}
      cond_13 = $signed(_y_13_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :597:41, :598:{32,41}, :602:31
      _xterm_T_39 = 32'h0 - _x_13_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:{32,41}, :603:33
      xterm_13 = cond_13 ? _xterm_T_39[31:13] : _x_13_T_1[31:13];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:{32,41}, :602:31, :603:{26,33}
      _yterm_T_39 = 32'h0 - _y_13_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:41, :598:{32,41}, :604:33
      yterm_13 = cond_13 ? _yterm_T_39[31:13] : _y_13_T_1[31:13];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:41, :598:{32,41}, :602:31, :604:{26,33}
      cond_14 = $signed(yr_7) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _xterm_T_42 = 32'h0 - xr_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28, :593:33
      xterm_14 = cond_14 ? _xterm_T_42[31:14] : xr_7[31:14];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :591:31, :593:{26,33}
      _yterm_T_42 = 32'h0 - yr_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :593:33, :594:33
      yterm_14 = cond_14 ? _yterm_T_42[31:14] : yr_7[31:14];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :591:31, :593:33, :594:{26,33}
      _x_15_T_1 = {{14{yterm_14[17]}}, yterm_14} + xr_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :594:26, :597:{32,41}
      _y_15_T_1 = yr_7 - {{14{xterm_14[17]}}, xterm_14};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :593:26, :597:41, :598:{32,41}
      cond_15 = $signed(_y_15_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :597:41, :598:{32,41}, :602:31
      _xterm_T_45 = 32'h0 - _x_15_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:{32,41}, :603:33
      xterm_15 = cond_15 ? _xterm_T_45[31:15] : _x_15_T_1[31:15];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:{32,41}, :602:31, :603:{26,33}
      _yterm_T_45 = 32'h0 - _y_15_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:41, :598:{32,41}, :604:33
      yterm_15 = cond_15 ? _yterm_T_45[31:15] : _y_15_T_1[31:15];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:41, :598:{32,41}, :602:31, :604:{26,33}
      cond_16 = $signed(yr_8) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _xterm_T_48 = 32'h0 - xr_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28, :593:33
      xterm_16 = cond_16 ? _xterm_T_48[31:16] : xr_8[31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :591:31, :593:{26,33}
      _yterm_T_48 = 32'h0 - yr_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :593:33, :594:33
      yterm_16 = cond_16 ? _yterm_T_48[31:16] : yr_8[31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :591:31, :593:33, :594:{26,33}
      _x_17_T_1 = {{16{yterm_16[15]}}, yterm_16} + xr_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:117:17, :265:19, :594:26, :597:{32,41}
      _y_17_T_1 = yr_8 - {{16{xterm_16[15]}}, xterm_16};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:117:17, :266:19, :593:26, :598:{32,41}
      cond_17 = $signed(_y_17_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :117:17, :297:28, :598:{32,41}, :602:31
      _xterm_T_51 = 32'h0 - _x_17_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :117:17, :297:28, :593:33, :597:{32,41}, :603:33
      xterm_17 = cond_17 ? _xterm_T_51[31:17] : _x_17_T_1[31:17];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:117:17, :593:33, :597:{32,41}, :602:31, :603:{26,33}
      _yterm_T_51 = 32'h0 - _y_17_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :117:17, :297:28, :593:33, :598:{32,41}, :604:33
      yterm_17 = cond_17 ? _yterm_T_51[31:17] : _y_17_T_1[31:17];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:117:17, :593:33, :598:{32,41}, :602:31, :604:{26,33}
      cond_18 = $signed(yr_9) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _xterm_T_54 = 32'h0 - xr_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28, :593:33
      xterm_18 = cond_18 ? _xterm_T_54[31:18] : xr_9[31:18];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :591:31, :593:{26,33}
      _yterm_T_54 = 32'h0 - yr_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :593:33, :594:33
      yterm_18 = cond_18 ? _yterm_T_54[31:18] : yr_9[31:18];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :591:31, :593:33, :594:{26,33}
      _x_19_T_1 = {{18{yterm_18[13]}}, yterm_18} + xr_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :594:26, :597:{32,41}
      _y_19_T_1 = yr_9 - {{18{xterm_18[13]}}, xterm_18};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :593:26, :597:41, :598:{32,41}
      cond_19 = $signed(_y_19_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :597:41, :598:{32,41}, :602:31
      _xterm_T_57 = 32'h0 - _x_19_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:{32,41}, :603:33
      xterm_19 = cond_19 ? _xterm_T_57[31:19] : _x_19_T_1[31:19];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:{32,41}, :602:31, :603:{26,33}
      _yterm_T_57 = 32'h0 - _y_19_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:41, :598:{32,41}, :604:33
      yterm_19 = cond_19 ? _yterm_T_57[31:19] : _y_19_T_1[31:19];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:41, :598:{32,41}, :602:31, :604:{26,33}
      cond_20 = $signed(yr_10) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _xterm_T_60 = 32'h0 - xr_10;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28, :593:33
      xterm_20 = cond_20 ? _xterm_T_60[31:20] : xr_10[31:20];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :591:31, :593:{26,33}
      _yterm_T_60 = 32'h0 - yr_10;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :593:33, :594:33
      yterm_20 = cond_20 ? _yterm_T_60[31:20] : yr_10[31:20];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :591:31, :593:33, :594:{26,33}
      _x_21_T_1 = {{20{yterm_20[11]}}, yterm_20} + xr_10;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :594:26, :597:{32,41}
      _y_21_T_1 = yr_10 - {{20{xterm_20[11]}}, xterm_20};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :593:26, :597:41, :598:{32,41}
      cond_21 = $signed(_y_21_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :597:41, :598:{32,41}, :602:31
      _xterm_T_63 = 32'h0 - _x_21_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:{32,41}, :603:33
      xterm_21 = cond_21 ? _xterm_T_63[31:21] : _x_21_T_1[31:21];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:{32,41}, :602:31, :603:{26,33}
      _yterm_T_63 = 32'h0 - _y_21_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:41, :598:{32,41}, :604:33
      yterm_21 = cond_21 ? _yterm_T_63[31:21] : _y_21_T_1[31:21];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:41, :598:{32,41}, :602:31, :604:{26,33}
      cond_22 = $signed(yr_11) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _xterm_T_66 = 32'h0 - xr_11;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28, :593:33
      xterm_22 = cond_22 ? _xterm_T_66[31:22] : xr_11[31:22];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :591:31, :593:{26,33}
      _yterm_T_66 = 32'h0 - yr_11;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :593:33, :594:33
      yterm_22 = cond_22 ? _yterm_T_66[31:22] : yr_11[31:22];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :591:31, :593:33, :594:{26,33}
      _x_23_T_1 = {{22{yterm_22[9]}}, yterm_22} + xr_11;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :594:26, :597:{32,41}
      _y_23_T_1 = yr_11 - {{22{xterm_22[9]}}, xterm_22};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :593:26, :597:41, :598:{32,41}
      cond_23 = $signed(_y_23_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :597:41, :598:{32,41}, :602:31
      _xterm_T_69 = 32'h0 - _x_23_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:{32,41}, :603:33
      xterm_23 = cond_23 ? _xterm_T_69[31:23] : _x_23_T_1[31:23];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:{32,41}, :602:31, :603:{26,33}
      _yterm_T_69 = 32'h0 - _y_23_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:41, :598:{32,41}, :604:33
      yterm_23 = cond_23 ? _yterm_T_69[31:23] : _y_23_T_1[31:23];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:41, :598:{32,41}, :602:31, :604:{26,33}
      cond_24 = $signed(yr_12) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _xterm_T_72 = 32'h0 - xr_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28, :593:33
      xterm_24 = cond_24 ? _xterm_T_72[31:24] : xr_12[31:24];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :591:31, :593:{26,33}
      _yterm_T_72 = 32'h0 - yr_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :593:33, :594:33
      yterm_24 = cond_24 ? _yterm_T_72[31:24] : yr_12[31:24];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :591:31, :593:33, :594:{26,33}
      _x_25_T_1 = {{24{yterm_24[7]}}, yterm_24} + xr_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :594:26, :597:{32,41}
      _y_25_T_1 = yr_12 - {{24{xterm_24[7]}}, xterm_24};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :593:26, :597:41, :598:{32,41}
      cond_25 = $signed(_y_25_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :597:41, :598:{32,41}, :602:31
      _xterm_T_75 = 32'h0 - _x_25_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:{32,41}, :603:33
      xterm_25 = cond_25 ? _xterm_T_75[31:25] : _x_25_T_1[31:25];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:{32,41}, :602:31, :603:{26,33}
      _yterm_T_75 = 32'h0 - _y_25_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:41, :598:{32,41}, :604:33
      yterm_25 = cond_25 ? _yterm_T_75[31:25] : _y_25_T_1[31:25];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:41, :598:{32,41}, :602:31, :604:{26,33}
      cond_26 = $signed(yr_13) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _xterm_T_78 = 32'h0 - xr_13;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28, :593:33
      xterm_26 = cond_26 ? _xterm_T_78[31:26] : xr_13[31:26];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :591:31, :593:{26,33}
      _yterm_T_78 = 32'h0 - yr_13;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :593:33, :594:33
      yterm_26 = cond_26 ? _yterm_T_78[31:26] : yr_13[31:26];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :591:31, :593:33, :594:{26,33}
      _x_27_T_1 = {{26{yterm_26[5]}}, yterm_26} + xr_13;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :594:26, :597:{32,41}
      _y_27_T_1 = yr_13 - {{26{xterm_26[5]}}, xterm_26};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :593:26, :597:41, :598:{32,41}
      cond_27 = $signed(_y_27_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :597:41, :598:{32,41}, :602:31
      _xterm_T_81 = 32'h0 - _x_27_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:{32,41}, :603:33
      xterm_27 = cond_27 ? _xterm_T_81[31:27] : _x_27_T_1[31:27];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:{32,41}, :602:31, :603:{26,33}
      _yterm_T_81 = 32'h0 - _y_27_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:41, :598:{32,41}, :604:33
      yterm_27 = cond_27 ? _yterm_T_81[31:27] : _y_27_T_1[31:27];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:41, :598:{32,41}, :602:31, :604:{26,33}
      cond_28 = $signed(yr_14) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _xterm_T_84 = 32'h0 - xr_14;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28, :593:33
      xterm_28 = cond_28 ? _xterm_T_84[31:28] : xr_14[31:28];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :591:31, :593:{26,33}
      _yterm_T_84 = 32'h0 - yr_14;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :593:33, :594:33
      yterm_28 = cond_28 ? _yterm_T_84[31:28] : yr_14[31:28];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :591:31, :593:33, :594:{26,33}
      _x_29_T_1 = {{28{yterm_28[3]}}, yterm_28} + xr_14;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :594:26, :597:{32,41}
      _y_29_T_1 = yr_14 - {{28{xterm_28[3]}}, xterm_28};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :593:26, :597:41, :598:{32,41}
      cond_29 = $signed(_y_29_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :597:41, :598:{32,41}, :602:31
      _xterm_T_87 = 32'h0 - _x_29_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:{32,41}, :603:33
      xterm_29 = cond_29 ? _xterm_T_87[31:29] : _x_29_T_1[31:29];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:{32,41}, :602:31, :603:{26,33}
      _yterm_T_87 = 32'h0 - _y_29_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:41, :598:{32,41}, :604:33
      yterm_29 = cond_29 ? _yterm_T_87[31:29] : _y_29_T_1[31:29];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:593:33, :597:41, :598:{32,41}, :602:31, :604:{26,33}
      cond_30 = $signed(yr_15) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :591:31
      _xterm_T_90 = 32'h0 - xr_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :297:28, :593:33
      xterm_30 = cond_30 ? _xterm_T_90[31:30] : xr_15[31:30];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :591:31, :593:{26,33}
      _yterm_T_90 = 32'h0 - yr_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :297:28, :593:33, :594:33
      yterm_30 = cond_30 ? _yterm_T_90[31:30] : yr_15[31:30];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :591:31, :593:33, :594:{26,33}
      _x_31_T_1 = {{30{yterm_30[1]}}, yterm_30} + xr_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :594:26, :597:{32,41}
      _y_31_T_1 = yr_15 - {{30{xterm_30[1]}}, xterm_30};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :593:26, :597:41, :598:{32,41}
      cond_31 = $signed(_y_31_T_1) < 32'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :597:41, :598:{32,41}, :602:31
      xr_0 <= _tofixedx0_io_out;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :295:28
      xr_1 <= {yterm_1[30], yterm_1} + _x_1_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:86:19, :265:19, :597:32, :604:26, :607:{32,41}
      xr_2 <= {{3{yterm_3[28]}}, yterm_3} + _x_3_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:84:19, :85:19, :265:19, :597:{32,41}, :604:26, :607:{32,41}
      xr_3 <= {{5{yterm_5[26]}}, yterm_5} + _x_5_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :265:19, :597:{32,41}, :604:26, :607:{32,41}
      xr_4 <= {{7{yterm_7[24]}}, yterm_7} + _x_7_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :265:19, :597:{32,41}, :604:26, :607:{32,41}
      xr_5 <= {{9{yterm_9[22]}}, yterm_9} + _x_9_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :265:19, :597:{32,41}, :604:26, :607:{32,41}
      xr_6 <= {{11{yterm_11[20]}}, yterm_11} + _x_11_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :597:{32,41}, :604:26, :607:{32,41}
      xr_7 <= {{13{yterm_13[18]}}, yterm_13} + _x_13_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:82:18, :265:19, :597:{32,41}, :604:26, :607:{32,41}
      xr_8 <= {{15{yterm_15[16]}}, yterm_15} + _x_15_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :597:{32,41}, :604:26, :607:{32,41}
      xr_9 <= {{17{yterm_17[14]}}, yterm_17} + _x_17_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:117:17, :265:19, :597:{32,41}, :604:26, :607:{32,41}
      xr_10 <= {{19{yterm_19[12]}}, yterm_19} + _x_19_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :597:{32,41}, :604:26, :607:{32,41}
      xr_11 <= {{21{yterm_21[10]}}, yterm_21} + _x_21_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :597:{32,41}, :604:26, :607:{32,41}
      xr_12 <= {{23{yterm_23[8]}}, yterm_23} + _x_23_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :597:{32,41}, :604:26, :607:{32,41}
      xr_13 <= {{25{yterm_25[6]}}, yterm_25} + _x_25_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:81:18, :265:19, :597:{32,41}, :604:26, :607:{32,41}
      xr_14 <= {{27{yterm_27[4]}}, yterm_27} + _x_27_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :597:{32,41}, :604:26, :607:{32,41}
      xr_15 <= {{29{yterm_29[2]}}, yterm_29} + _x_29_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :597:{32,41}, :604:26, :607:{32,41}
      _yterm_T_93 = 32'h0 - _y_31_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:41, :598:{32,41}, :604:33
      xr_16 <= {32{cond_31 ? _yterm_T_93[31] : _y_31_T_1[31]}} + _x_31_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :593:33, :597:{32,41}, :598:{32,41}, :602:31, :604:{26,33}, :607:{32,41}
      yr_0 <= _tofixedy0_io_out;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :296:28
      yr_1 <= _y_1_T_1 - {xterm_1[30], xterm_1};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:86:19, :266:19, :598:32, :603:26, :608:{32,41}
      yr_2 <= _y_3_T_1 - {{3{xterm_3[28]}}, xterm_3};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:84:19, :85:19, :266:19, :598:{32,41}, :603:26, :608:{32,41}
      yr_3 <= _y_5_T_1 - {{5{xterm_5[26]}}, xterm_5};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :266:19, :598:{32,41}, :603:26, :607:41, :608:{32,41}
      yr_4 <= _y_7_T_1 - {{7{xterm_7[24]}}, xterm_7};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :266:19, :598:{32,41}, :603:26, :607:41, :608:{32,41}
      yr_5 <= _y_9_T_1 - {{9{xterm_9[22]}}, xterm_9};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :266:19, :598:{32,41}, :603:26, :607:41, :608:{32,41}
      yr_6 <= _y_11_T_1 - {{11{xterm_11[20]}}, xterm_11};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :597:41, :598:{32,41}, :603:26, :607:41, :608:{32,41}
      yr_7 <= _y_13_T_1 - {{13{xterm_13[18]}}, xterm_13};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:82:18, :266:19, :597:41, :598:{32,41}, :603:26, :608:{32,41}
      yr_8 <= _y_15_T_1 - {{15{xterm_15[16]}}, xterm_15};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :597:41, :598:{32,41}, :603:26, :607:41, :608:{32,41}
      yr_9 <= _y_17_T_1 - {{17{xterm_17[14]}}, xterm_17};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:117:17, :266:19, :598:{32,41}, :603:26, :607:41, :608:{32,41}
      yr_10 <= _y_19_T_1 - {{19{xterm_19[12]}}, xterm_19};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :597:41, :598:{32,41}, :603:26, :607:41, :608:{32,41}
      yr_11 <= _y_21_T_1 - {{21{xterm_21[10]}}, xterm_21};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :597:41, :598:{32,41}, :603:26, :607:41, :608:{32,41}
      yr_12 <= _y_23_T_1 - {{23{xterm_23[8]}}, xterm_23};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :597:41, :598:{32,41}, :603:26, :607:41, :608:{32,41}
      yr_13 <= _y_25_T_1 - {{25{xterm_25[6]}}, xterm_25};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:81:18, :266:19, :597:41, :598:{32,41}, :603:26, :608:{32,41}
      yr_14 <= _y_27_T_1 - {{27{xterm_27[4]}}, xterm_27};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :597:41, :598:{32,41}, :603:26, :607:41, :608:{32,41}
      yr_15 <= _y_29_T_1 - {{29{xterm_29[2]}}, xterm_29};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :597:41, :598:{32,41}, :603:26, :607:41, :608:{32,41}
      _xterm_T_93 = 32'h0 - _x_31_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28, :593:33, :597:{32,41}, :603:33
      yr_16 <= _y_31_T_1 - {32{cond_31 ? _xterm_T_93[31] : _x_31_T_1[31]}};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :593:33, :597:{32,41}, :598:{32,41}, :602:31, :603:{26,33}, :607:41, :608:{32,41}
      zr_0 <= _tofixedz0_io_out;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19, :297:28
      zr_1 <=
        zr_0 + (cond ? 32'hF36F0250 : 32'hC90FDB0)
        + (cond_1 ? 32'hF894E640 : 32'h76B19C0);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:93:16, :94:16, :267:19, :591:31, :595:{26,33}, :602:31, :605:{26,33}, :609:32
      zr_2 <=
        zr_1 + (cond_2 ? 32'hFC149140 : 32'h3EB6EC0)
        + (cond_3 ? 32'hFE02A456 : 32'h1FD5BAA);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:95:16, :96:16, :267:19, :591:31, :595:{26,33}, :602:31, :605:{26,33}, :609:32
      zr_3 <=
        zr_2 + (cond_4 ? 32'hFF005522 : 32'hFFAADE)
        + (cond_5 ? 32'hFF800AA9 : 32'h7FF557);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:97:16, :98:16, :267:19, :591:31, :595:{26,33}, :602:31, :605:{26,33}, :609:32
      zr_4 <=
        zr_3 + (cond_6 ? 32'hFFC00156 : 32'h3FFEAA)
        + (cond_7 ? 32'hFFE0002B : 32'h1FFFD5);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:99:16, :100:16, :267:19, :591:31, :595:{26,33}, :602:31, :605:{26,33}, :609:32
      zr_5 <=
        zr_4 + (cond_8 ? 32'hFFF00006 : 32'hFFFFA) + (cond_9 ? 32'hFFF80001 : 32'h7FFFF);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:101:16, :102:16, :267:19, :591:31, :595:{26,33}, :602:31, :605:{26,33}, :609:32
      zr_6 <=
        zr_5 + (cond_10 ? 32'hFFFC0001 : 32'h3FFFF)
        + (cond_11 ? 32'hFFFE0001 : 32'h1FFFF);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:103:17, :104:17, :267:19, :591:31, :595:{26,33}, :602:31, :605:{26,33}, :609:32
      zr_7 <=
        zr_6 + (cond_12 ? 32'hFFFF0000 : 32'h10000) + (cond_13 ? 32'hFFFF8000 : 32'h8000);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:105:17, :106:17, :267:19, :591:31, :595:{26,33}, :602:31, :605:{26,33}, :609:32
      zr_8 <=
        zr_7 + (cond_14 ? 32'hFFFFC000 : 32'h4000) + (cond_15 ? 32'hFFFFE000 : 32'h2000);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:107:17, :108:17, :267:19, :591:31, :595:{26,33}, :602:31, :605:{26,33}, :609:32
      zr_9 <=
        zr_8 + (cond_16 ? 32'hFFFFF000 : 32'h1000) + (cond_17 ? 32'hFFFFF800 : 32'h800);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:109:17, :110:17, :267:19, :591:31, :595:{26,33}, :602:31, :605:{26,33}, :609:32
      zr_10 <=
        zr_9 + (cond_18 ? 32'hFFFFFC00 : 32'h400) + (cond_19 ? 32'hFFFFFE00 : 32'h200);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:111:17, :112:17, :267:19, :591:31, :595:{26,33}, :602:31, :605:{26,33}, :609:32
      zr_11 <=
        zr_10 + (cond_20 ? 32'hFFFFFF00 : 32'h100) + (cond_21 ? 32'hFFFFFF80 : 32'h80);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:113:17, :114:17, :267:19, :591:31, :595:{26,33}, :602:31, :605:{26,33}, :609:32
      zr_12 <=
        zr_11 + (cond_22 ? 32'hFFFFFFC0 : 32'h40) + (cond_23 ? 32'hFFFFFFE0 : 32'h20);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:115:17, :116:17, :267:19, :591:31, :595:{26,33}, :602:31, :605:{26,33}, :609:32
      zr_13 <=
        zr_12 + (cond_24 ? 32'hFFFFFFF0 : 32'h10) + (cond_25 ? 32'hFFFFFFF8 : 32'h8);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:117:17, :118:17, :267:19, :591:31, :595:{26,33}, :602:31, :605:{26,33}, :609:32
      zr_14 <=
        zr_13 + (cond_26 ? 32'hFFFFFFFC : 32'h4) + (cond_27 ? 32'hFFFFFFFE : 32'h2);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:85:19, :119:17, :267:19, :591:31, :595:{26,33}, :602:31, :605:{26,33}, :609:32
      zr_15 <= zr_14 + (cond_28 ? 32'hFFFFFFFF : 32'h1);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:86:19, :267:19, :591:31, :595:{26,33}, :599:32
      zr_16 <= zr_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
      `FIRRTL_BEFORE_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
      automatic logic [31:0] _RANDOM[0:82];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
        `INIT_RANDOM_PROLOG_	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
        for (logic [6:0] i = 7'h0; i < 7'h53; i += 7'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
        end	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
        xr_0 = _RANDOM[7'h0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_1 = _RANDOM[7'h1];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_2 = _RANDOM[7'h2];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_3 = _RANDOM[7'h3];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_4 = _RANDOM[7'h4];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_5 = _RANDOM[7'h5];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_6 = _RANDOM[7'h6];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_7 = _RANDOM[7'h7];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_8 = _RANDOM[7'h8];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_9 = _RANDOM[7'h9];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_10 = _RANDOM[7'hA];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_11 = _RANDOM[7'hB];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_12 = _RANDOM[7'hC];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_13 = _RANDOM[7'hD];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_14 = _RANDOM[7'hE];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_15 = _RANDOM[7'hF];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_16 = _RANDOM[7'h10];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        yr_0 = _RANDOM[7'h21];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_1 = _RANDOM[7'h22];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_2 = _RANDOM[7'h23];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_3 = _RANDOM[7'h24];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_4 = _RANDOM[7'h25];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_5 = _RANDOM[7'h26];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_6 = _RANDOM[7'h27];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_7 = _RANDOM[7'h28];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_8 = _RANDOM[7'h29];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_9 = _RANDOM[7'h2A];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_10 = _RANDOM[7'h2B];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_11 = _RANDOM[7'h2C];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_12 = _RANDOM[7'h2D];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_13 = _RANDOM[7'h2E];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_14 = _RANDOM[7'h2F];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_15 = _RANDOM[7'h30];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_16 = _RANDOM[7'h31];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        zr_0 = _RANDOM[7'h42];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_1 = _RANDOM[7'h43];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_2 = _RANDOM[7'h44];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_3 = _RANDOM[7'h45];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_4 = _RANDOM[7'h46];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_5 = _RANDOM[7'h47];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_6 = _RANDOM[7'h48];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_7 = _RANDOM[7'h49];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_8 = _RANDOM[7'h4A];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_9 = _RANDOM[7'h4B];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_10 = _RANDOM[7'h4C];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_11 = _RANDOM[7'h4D];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_12 = _RANDOM[7'h4E];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_13 = _RANDOM[7'h4F];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_14 = _RANDOM[7'h50];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_15 = _RANDOM[7'h51];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_16 = _RANDOM[7'h52];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
      `FIRRTL_AFTER_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FloatToFixed32 tofixedx0 (	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:295:28
    .io_in  (32'h3F800000),	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :295:28
    .io_out (_tofixedx0_io_out)
  );
  FloatToFixed32 tofixedy0 (	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:296:28
    .io_in  (io_in_y0),
    .io_out (_tofixedy0_io_out)
  );
  FloatToFixed32 tofixedz0 (	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:297:28
    .io_in  (32'h0),	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :297:28
    .io_out (_tofixedz0_io_out)
  );
  FixedToFloat32 tofloatxout (	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:620:29
    .io_in  (xr_16),	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
    .io_out (/* unused */)
  );
  FixedToFloat32 tofloatyout (	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:621:29
    .io_in  (yr_16),	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
    .io_out (/* unused */)
  );
  FixedToFloat32 tofloatzout (	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:622:29
    .io_in  (zr_16),	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
    .io_out (io_out_z)
  );
endmodule

module Atan_n32_pd8_bw32(	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
  input         clock,	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
                reset,	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
  input  [31:0] io_in,	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:14:14
  output [31:0] io_out,	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:14:14
  input         io_ready,	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:14:14
  output        io_valid	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:14:14
);

  wire [31:0] inputmag = {1'h0, io_in[30:0]};	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:49:{24,32}
  reg  [31:0] shift_reg_0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_10;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_11;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_13;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_14;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_16;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [31:0] shift_reg_17;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  always @(posedge clock) begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
    if (reset) begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
      shift_reg_0 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_1 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_2 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_3 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_4 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_5 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_6 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_7 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_8 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_9 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_10 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_11 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_12 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_13 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_14 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_15 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_16 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_17 <= 32'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
    end
    else begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
      shift_reg_0 <= {31'h0, io_ready};	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26, :135:16
      shift_reg_1 <= shift_reg_0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_2 <= shift_reg_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_3 <= shift_reg_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_4 <= shift_reg_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_5 <= shift_reg_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_6 <= shift_reg_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_7 <= shift_reg_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_8 <= shift_reg_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_9 <= shift_reg_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_10 <= shift_reg_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_11 <= shift_reg_10;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_12 <= shift_reg_11;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_13 <= shift_reg_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_14 <= shift_reg_13;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_15 <= shift_reg_14;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_16 <= shift_reg_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_17 <= shift_reg_16;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
      `FIRRTL_BEFORE_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
      automatic logic [31:0] _RANDOM[0:17];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
        `INIT_RANDOM_PROLOG_	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
        for (logic [4:0] i = 5'h0; i < 5'h12; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
        end	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
        shift_reg_0 = _RANDOM[5'h0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_1 = _RANDOM[5'h1];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_2 = _RANDOM[5'h2];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_3 = _RANDOM[5'h3];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_4 = _RANDOM[5'h4];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_5 = _RANDOM[5'h5];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_6 = _RANDOM[5'h6];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_7 = _RANDOM[5'h7];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_8 = _RANDOM[5'h8];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_9 = _RANDOM[5'h9];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_10 = _RANDOM[5'hA];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_11 = _RANDOM[5'hB];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_12 = _RANDOM[5'hC];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_13 = _RANDOM[5'hD];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_14 = _RANDOM[5'hE];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_15 = _RANDOM[5'hF];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_16 = _RANDOM[5'h10];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_17 = _RANDOM[5'h11];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
      `FIRRTL_AFTER_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  VCORDIC vcordic (	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:50:25
    .clock    (clock),
    .reset    (reset),
    .io_in_y0
      ($signed(inputmag) > 32'sh4B189680
         ? {io_in[31], 31'h4B189680}
         : $signed(inputmag) < 32'sh322BCC78 ? {io_in[31], 31'h322BCC77} : io_in),	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:48:26, :49:24, :52:{27,44,72}, :53:{10,27,56}
    .io_out_z (io_out)
  );
  assign io_valid = shift_reg_17[0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26, :139:12
endmodule

