// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module FloatToFixed16(	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:17:7
  input  [15:0] io_in,	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:20:14
  output [15:0] io_out	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:20:14
);

  wire [4:0]  _shiftamt_T = io_in[14:10] - 5'hF;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:26:25, :28:23
  wire [18:0] _data_T_9 = {7'h1, io_in[9:0], 2'h0} >> 5'h0 - _shiftamt_T;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:25:{39,47}, :28:23, :31:{36,44,48}
  wire [49:0] _data_T_14 = {38'h1, io_in[9:0], 2'h0} << _shiftamt_T;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:25:47, :28:23, :31:36, :32:44
  wire [15:0] data = _shiftamt_T[4] ? _data_T_9[15:0] : _data_T_14[15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:28:23, :30:{17,26}, :31:44, :32:44
  assign io_out = io_in[15] ? 16'h0 - data : data;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:17:7, :27:26, :30:17, :31:48, :33:{16,40}
endmodule

module CLZ16(	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:105:7
  input  [15:0] io_in,	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:106:14
  output [4:0]  io_out	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:106:14
);

  wire [6:0] bx = (|(io_in[15:8])) ? io_in[15:9] : io_in[7:1];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:106:14, :114:{15,20,33,45}
  wire [2:0] cx = (|(bx[6:3])) ? bx[6:4] : bx[2:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:114:15, :115:{15,20,33,45}
  assign io_out =
    io_in == 16'h0
      ? 5'h10
      : {1'h0,
         ~(|(io_in[15:8])),
         ~(|(bx[6:3])),
         ~(|(cx[2:1])),
         ~((|(cx[2:1])) ? cx[2] : cx[0])};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:105:7, :114:{15,20,33}, :115:{15,20,33}, :116:{15,20,33,45}, :119:{33,63,93}, :120:23, :121:{16,23}
endmodule

module FixedToFloat(	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:319:7
  input  [15:0] io_in,	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:320:14
  output [15:0] io_out	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:320:14
);

  wire [4:0]      _clz16_io_out;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:337:23
  wire [15:0]     data = io_in[15] ? ~io_in + 16'h1 : io_in;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:334:{14,20,37,52}
  wire [524302:0] _frac_T_3 =
    {{524287{data[15]}}, data} << {15'h0, _clz16_io_out[3:0]} + 19'h1;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:334:14, :337:23, :340:{34,49}, :342:{28,45}
  CLZ16 clz16 (	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:337:23
    .io_in  (data),	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:334:14
    .io_out (_clz16_io_out)
  );
  assign io_out = {io_in[15], 5'h3 - {1'h0, _clz16_io_out[3:0]} + 5'hF, _frac_T_3[15:6]};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\FixedPoint.scala:319:7, :334:20, :337:23, :340:49, :341:{25,48}, :342:{10,28}, :343:39
endmodule

module VCORDIC(	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
  input         clock,	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
                reset,	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
  input  [15:0] io_in_y0,	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14
  output [15:0] io_out_z	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14
);

  wire [15:0] _tofixedz0_io_out;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:229:27
  wire [15:0] _tofixedy0_io_out;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:228:27
  wire [15:0] _tofixedx0_io_out;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:227:27
  reg  [15:0] xr_0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_1;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_2;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_3;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_4;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_5;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_6;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_7;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_8;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_9;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_10;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_11;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_12;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_13;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_14;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_15;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] xr_16;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
  reg  [15:0] yr_0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_1;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_2;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_3;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_4;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_5;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_6;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_7;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_8;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_9;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_10;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_11;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_12;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_13;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_14;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_15;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] yr_16;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
  reg  [15:0] zr_0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_1;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_2;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_3;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_4;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_5;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_6;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_7;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_8;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_9;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_10;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_11;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_12;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_13;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_14;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_15;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  reg  [15:0] zr_16;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
  always @(posedge clock) begin	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
    if (reset) begin	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
      xr_0 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_1 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_2 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_3 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_4 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_5 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_6 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_7 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_8 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_9 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_10 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_11 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_12 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_13 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_14 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_15 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      xr_16 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27
      yr_0 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_1 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_2 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_3 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_4 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_5 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_6 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_7 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_8 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_9 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_10 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_11 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_12 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_13 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_14 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_15 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      yr_16 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27
      zr_0 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_1 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_2 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_3 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_4 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_5 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_6 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_7 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_8 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_9 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_10 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_11 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_12 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_13 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_14 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_15 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
      zr_16 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :224:19, :229:27
    end
    else begin	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
      automatic logic        _fxthetaterm_T;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic        _fxthetaterm_T_3;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic [15:0] _fxxterm_T_5;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44
      automatic logic [14:0] fxxterm_1;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:24
      automatic logic [15:0] _fxyterm_T_5;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44, :308:44
      automatic logic [14:0] fxyterm_1;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:308:24
      automatic logic        _fxthetaterm_T_6;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic [15:0] _fxxterm_T_9;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44
      automatic logic [13:0] fxxterm_2;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:24
      automatic logic [15:0] _fxyterm_T_9;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44, :308:44
      automatic logic [13:0] fxyterm_2;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:308:24
      automatic logic        _fxthetaterm_T_9;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic [15:0] _fxxterm_T_13;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44
      automatic logic [12:0] fxxterm_3;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:24
      automatic logic [15:0] _fxyterm_T_13;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44, :308:44
      automatic logic [12:0] fxyterm_3;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:308:24
      automatic logic        _fxthetaterm_T_12;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic [15:0] _fxxterm_T_17;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44
      automatic logic [11:0] fxxterm_4;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:24
      automatic logic [15:0] _fxyterm_T_17;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44, :308:44
      automatic logic [11:0] fxyterm_4;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:308:24
      automatic logic        _fxthetaterm_T_15;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic [15:0] _fxxterm_T_21;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44
      automatic logic [10:0] fxxterm_5;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:24
      automatic logic [15:0] _fxyterm_T_21;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44, :308:44
      automatic logic [10:0] fxyterm_5;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:308:24
      automatic logic        _fxthetaterm_T_18;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic [15:0] _fxxterm_T_25;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44
      automatic logic [9:0]  fxxterm_6;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:24
      automatic logic [15:0] _fxyterm_T_25;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44, :308:44
      automatic logic [9:0]  fxyterm_6;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:308:24
      automatic logic        _fxthetaterm_T_21;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic [15:0] _fxxterm_T_29;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44
      automatic logic [8:0]  fxxterm_7;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:24
      automatic logic [15:0] _fxyterm_T_29;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44, :308:44
      automatic logic [8:0]  fxyterm_7;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:308:24
      automatic logic        _fxthetaterm_T_24;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic [15:0] _fxxterm_T_33;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44
      automatic logic [7:0]  fxxterm_8;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:24
      automatic logic [15:0] _fxyterm_T_33;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44, :308:44
      automatic logic [7:0]  fxyterm_8;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:308:24
      automatic logic        _fxthetaterm_T_27;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic [15:0] _fxxterm_T_37;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44
      automatic logic [6:0]  fxxterm_9;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:24
      automatic logic [15:0] _fxyterm_T_37;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44, :308:44
      automatic logic [6:0]  fxyterm_9;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:308:24
      automatic logic        _fxthetaterm_T_30;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic [15:0] _fxxterm_T_41;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44
      automatic logic [5:0]  fxxterm_10;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:24
      automatic logic [15:0] _fxyterm_T_41;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44, :308:44
      automatic logic [5:0]  fxyterm_10;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:308:24
      automatic logic        _fxthetaterm_T_33;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic [15:0] _fxxterm_T_45;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44
      automatic logic [4:0]  fxxterm_11;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:24
      automatic logic [15:0] _fxyterm_T_45;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44, :308:44
      automatic logic [4:0]  fxyterm_11;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:308:24
      automatic logic        _fxthetaterm_T_36;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic [15:0] _fxxterm_T_49;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44
      automatic logic [3:0]  fxxterm_12;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:24
      automatic logic [15:0] _fxyterm_T_49;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44, :308:44
      automatic logic [3:0]  fxyterm_12;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:308:24
      automatic logic        _fxthetaterm_T_39;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic [15:0] _fxxterm_T_53;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44
      automatic logic [2:0]  fxxterm_13;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:24
      automatic logic [15:0] _fxyterm_T_53;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44, :308:44
      automatic logic [2:0]  fxyterm_13;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:308:24
      automatic logic        _fxthetaterm_T_42;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic [15:0] _fxxterm_T_57;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44
      automatic logic [1:0]  fxxterm_14;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:24
      automatic logic [15:0] _fxyterm_T_57;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44, :308:44
      automatic logic [1:0]  fxyterm_14;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:308:24
      automatic logic        _fxthetaterm_T_45;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:31
      automatic logic [15:0] _fxyterm_T_61;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44, :308:44
      automatic logic [15:0] _fxxterm_T_61;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:307:44
      _fxthetaterm_T = $signed(yr_0) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      _fxthetaterm_T_3 = $signed(yr_1) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      _fxxterm_T_5 = 16'h0 - xr_1;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27, :307:44
      fxxterm_1 = _fxthetaterm_T_3 ? _fxxterm_T_5[15:1] : xr_1[15:1];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :307:{24,31,44}
      _fxyterm_T_5 = 16'h0 - yr_1;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:44, :308:44
      fxyterm_1 = _fxthetaterm_T_3 ? _fxyterm_T_5[15:1] : yr_1[15:1];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:{31,44}, :308:{24,44}
      _fxthetaterm_T_6 = $signed(yr_2) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      _fxxterm_T_9 = 16'h0 - xr_2;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27, :307:44
      fxxterm_2 = _fxthetaterm_T_6 ? _fxxterm_T_9[15:2] : xr_2[15:2];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :307:{24,31,44}
      _fxyterm_T_9 = 16'h0 - yr_2;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:44, :308:44
      fxyterm_2 = _fxthetaterm_T_6 ? _fxyterm_T_9[15:2] : yr_2[15:2];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:{31,44}, :308:{24,44}
      _fxthetaterm_T_9 = $signed(yr_3) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      _fxxterm_T_13 = 16'h0 - xr_3;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27, :307:44
      fxxterm_3 = _fxthetaterm_T_9 ? _fxxterm_T_13[15:3] : xr_3[15:3];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :307:{24,31,44}
      _fxyterm_T_13 = 16'h0 - yr_3;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:44, :308:44
      fxyterm_3 = _fxthetaterm_T_9 ? _fxyterm_T_13[15:3] : yr_3[15:3];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:{31,44}, :308:{24,44}
      _fxthetaterm_T_12 = $signed(yr_4) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      _fxxterm_T_17 = 16'h0 - xr_4;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27, :307:44
      fxxterm_4 = _fxthetaterm_T_12 ? _fxxterm_T_17[15:4] : xr_4[15:4];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :307:{24,31,44}
      _fxyterm_T_17 = 16'h0 - yr_4;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:44, :308:44
      fxyterm_4 = _fxthetaterm_T_12 ? _fxyterm_T_17[15:4] : yr_4[15:4];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:{31,44}, :308:{24,44}
      _fxthetaterm_T_15 = $signed(yr_5) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      _fxxterm_T_21 = 16'h0 - xr_5;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27, :307:44
      fxxterm_5 = _fxthetaterm_T_15 ? _fxxterm_T_21[15:5] : xr_5[15:5];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :307:{24,31,44}
      _fxyterm_T_21 = 16'h0 - yr_5;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:44, :308:44
      fxyterm_5 = _fxthetaterm_T_15 ? _fxyterm_T_21[15:5] : yr_5[15:5];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:{31,44}, :308:{24,44}
      _fxthetaterm_T_18 = $signed(yr_6) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      _fxxterm_T_25 = 16'h0 - xr_6;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27, :307:44
      fxxterm_6 = _fxthetaterm_T_18 ? _fxxterm_T_25[15:6] : xr_6[15:6];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :307:{24,31,44}
      _fxyterm_T_25 = 16'h0 - yr_6;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:44, :308:44
      fxyterm_6 = _fxthetaterm_T_18 ? _fxyterm_T_25[15:6] : yr_6[15:6];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:{31,44}, :308:{24,44}
      _fxthetaterm_T_21 = $signed(yr_7) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      _fxxterm_T_29 = 16'h0 - xr_7;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27, :307:44
      fxxterm_7 = _fxthetaterm_T_21 ? _fxxterm_T_29[15:7] : xr_7[15:7];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :307:{24,31,44}
      _fxyterm_T_29 = 16'h0 - yr_7;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:44, :308:44
      fxyterm_7 = _fxthetaterm_T_21 ? _fxyterm_T_29[15:7] : yr_7[15:7];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:{31,44}, :308:{24,44}
      _fxthetaterm_T_24 = $signed(yr_8) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      _fxxterm_T_33 = 16'h0 - xr_8;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27, :307:44
      fxxterm_8 = _fxthetaterm_T_24 ? _fxxterm_T_33[15:8] : xr_8[15:8];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :307:{24,31,44}
      _fxyterm_T_33 = 16'h0 - yr_8;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:44, :308:44
      fxyterm_8 = _fxthetaterm_T_24 ? _fxyterm_T_33[15:8] : yr_8[15:8];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:{31,44}, :308:{24,44}
      _fxthetaterm_T_27 = $signed(yr_9) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      _fxxterm_T_37 = 16'h0 - xr_9;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27, :307:44
      fxxterm_9 = _fxthetaterm_T_27 ? _fxxterm_T_37[15:9] : xr_9[15:9];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :307:{24,31,44}
      _fxyterm_T_37 = 16'h0 - yr_9;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:44, :308:44
      fxyterm_9 = _fxthetaterm_T_27 ? _fxyterm_T_37[15:9] : yr_9[15:9];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:{31,44}, :308:{24,44}
      _fxthetaterm_T_30 = $signed(yr_10) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      _fxxterm_T_41 = 16'h0 - xr_10;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27, :307:44
      fxxterm_10 = _fxthetaterm_T_30 ? _fxxterm_T_41[15:10] : xr_10[15:10];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :307:{24,31,44}
      _fxyterm_T_41 = 16'h0 - yr_10;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:44, :308:44
      fxyterm_10 = _fxthetaterm_T_30 ? _fxyterm_T_41[15:10] : yr_10[15:10];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:{31,44}, :308:{24,44}
      _fxthetaterm_T_33 = $signed(yr_11) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      _fxxterm_T_45 = 16'h0 - xr_11;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27, :307:44
      fxxterm_11 = _fxthetaterm_T_33 ? _fxxterm_T_45[15:11] : xr_11[15:11];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :307:{24,31,44}
      _fxyterm_T_45 = 16'h0 - yr_11;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:44, :308:44
      fxyterm_11 = _fxthetaterm_T_33 ? _fxyterm_T_45[15:11] : yr_11[15:11];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:{31,44}, :308:{24,44}
      _fxthetaterm_T_36 = $signed(yr_12) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      _fxxterm_T_49 = 16'h0 - xr_12;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27, :307:44
      fxxterm_12 = _fxthetaterm_T_36 ? _fxxterm_T_49[15:12] : xr_12[15:12];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :307:{24,31,44}
      _fxyterm_T_49 = 16'h0 - yr_12;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:44, :308:44
      fxyterm_12 = _fxthetaterm_T_36 ? _fxyterm_T_49[15:12] : yr_12[15:12];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:{31,44}, :308:{24,44}
      _fxthetaterm_T_39 = $signed(yr_13) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      _fxxterm_T_53 = 16'h0 - xr_13;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27, :307:44
      fxxterm_13 = _fxthetaterm_T_39 ? _fxxterm_T_53[15:13] : xr_13[15:13];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :307:{24,31,44}
      _fxyterm_T_53 = 16'h0 - yr_13;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:44, :308:44
      fxyterm_13 = _fxthetaterm_T_39 ? _fxyterm_T_53[15:13] : yr_13[15:13];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:{31,44}, :308:{24,44}
      _fxthetaterm_T_42 = $signed(yr_14) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      _fxxterm_T_57 = 16'h0 - xr_14;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27, :307:44
      fxxterm_14 = _fxthetaterm_T_42 ? _fxxterm_T_57[15:14] : xr_14[15:14];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :307:{24,31,44}
      _fxyterm_T_57 = 16'h0 - yr_14;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:44, :308:44
      fxyterm_14 = _fxthetaterm_T_42 ? _fxyterm_T_57[15:14] : yr_14[15:14];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:{31,44}, :308:{24,44}
      _fxthetaterm_T_45 = $signed(yr_15) < 16'sh0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:31
      xr_0 <= _tofixedx0_io_out;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :227:27
      xr_1 <= xr_0 + (_fxthetaterm_T ? 16'h0 - yr_0 : yr_0);	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :223:19, :229:27, :307:{31,44}, :308:{24,44}, :310:25
      xr_2 <= {fxyterm_1[14], fxyterm_1} + xr_1;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:48:19, :222:19, :308:24, :310:{25,36}
      xr_3 <= {{2{fxyterm_2[13]}}, fxyterm_2} + xr_2;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:47:19, :222:19, :308:24, :310:{25,36}
      xr_4 <= {{3{fxyterm_3[12]}}, fxyterm_3} + xr_3;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:46:19, :222:19, :308:24, :310:{25,36}
      xr_5 <= {{4{fxyterm_4[11]}}, fxyterm_4} + xr_4;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:80:17, :222:19, :308:24, :310:{25,36}
      xr_6 <= {{5{fxyterm_5[10]}}, fxyterm_5} + xr_5;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :308:24, :310:{25,36}
      xr_7 <= {{6{fxyterm_6[9]}}, fxyterm_6} + xr_6;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:45:18, :222:19, :308:24, :310:{25,36}
      xr_8 <= {{7{fxyterm_7[8]}}, fxyterm_7} + xr_7;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :308:24, :310:{25,36}
      xr_9 <= {{8{fxyterm_8[7]}}, fxyterm_8} + xr_8;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:79:17, :222:19, :308:24, :310:{25,36}
      xr_10 <= {{9{fxyterm_9[6]}}, fxyterm_9} + xr_9;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :308:24, :310:{25,36}
      xr_11 <= {{10{fxyterm_10[5]}}, fxyterm_10} + xr_10;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :308:24, :310:{25,36}
      xr_12 <= {{11{fxyterm_11[4]}}, fxyterm_11} + xr_11;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :308:24, :310:{25,36}
      xr_13 <= {{12{fxyterm_12[3]}}, fxyterm_12} + xr_12;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :308:24, :310:{25,36}
      xr_14 <= {{13{fxyterm_13[2]}}, fxyterm_13} + xr_13;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:44:18, :222:19, :308:24, :310:{25,36}
      xr_15 <= {{14{fxyterm_14[1]}}, fxyterm_14} + xr_14;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :308:24, :310:{25,36}
      _fxyterm_T_61 = 16'h0 - yr_15;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :223:19, :229:27, :307:44, :308:44
      xr_16 <= {16{_fxthetaterm_T_45 ? _fxyterm_T_61[15] : yr_15[15]}} + xr_15;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :223:19, :307:{31,44}, :308:{24,44}, :310:{25,36}
      yr_0 <= _tofixedy0_io_out;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :228:27
      yr_1 <= yr_0 - (_fxthetaterm_T ? 16'h0 - xr_0 : xr_0);	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :223:19, :229:27, :307:{24,31,44}, :311:25
      yr_2 <= yr_1 - {fxxterm_1[14], fxxterm_1};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:48:19, :223:19, :307:24, :311:{25,36}
      yr_3 <= yr_2 - {{2{fxxterm_2[13]}}, fxxterm_2};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:47:19, :223:19, :307:24, :311:{25,36}
      yr_4 <= yr_3 - {{3{fxxterm_3[12]}}, fxxterm_3};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:46:19, :223:19, :307:24, :311:{25,36}
      yr_5 <= yr_4 - {{4{fxxterm_4[11]}}, fxxterm_4};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:80:17, :223:19, :307:24, :311:{25,36}
      yr_6 <= yr_5 - {{5{fxxterm_5[10]}}, fxxterm_5};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:24, :310:36, :311:{25,36}
      yr_7 <= yr_6 - {{6{fxxterm_6[9]}}, fxxterm_6};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:45:18, :223:19, :307:24, :311:{25,36}
      yr_8 <= yr_7 - {{7{fxxterm_7[8]}}, fxxterm_7};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:24, :310:36, :311:{25,36}
      yr_9 <= yr_8 - {{8{fxxterm_8[7]}}, fxxterm_8};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:79:17, :223:19, :307:24, :311:{25,36}
      yr_10 <= yr_9 - {{9{fxxterm_9[6]}}, fxxterm_9};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:24, :310:36, :311:{25,36}
      yr_11 <= yr_10 - {{10{fxxterm_10[5]}}, fxxterm_10};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:24, :310:36, :311:{25,36}
      yr_12 <= yr_11 - {{11{fxxterm_11[4]}}, fxxterm_11};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:24, :310:36, :311:{25,36}
      yr_13 <= yr_12 - {{12{fxxterm_12[3]}}, fxxterm_12};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:24, :310:36, :311:{25,36}
      yr_14 <= yr_13 - {{13{fxxterm_13[2]}}, fxxterm_13};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:44:18, :223:19, :307:24, :311:{25,36}
      yr_15 <= yr_14 - {{14{fxxterm_14[1]}}, fxxterm_14};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19, :307:24, :310:36, :311:{25,36}
      _fxxterm_T_61 = 16'h0 - xr_15;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :222:19, :229:27, :307:44
      yr_16 <= yr_15 - {16{_fxthetaterm_T_45 ? _fxxterm_T_61[15] : xr_15[15]}};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19, :223:19, :307:{24,31,44}, :310:36, :311:{25,36}
      zr_0 <= _tofixedz0_io_out;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19, :229:27
      zr_1 <= zr_0 + (_fxthetaterm_T ? 16'hF36F : 16'hC91);	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:36:18, :224:19, :307:31, :309:{28,48}, :312:25
      zr_2 <= zr_1 + (_fxthetaterm_T_3 ? 16'hF9B8 : 16'h648);	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:37:18, :224:19, :307:31, :309:{28,48}, :312:25
      zr_3 <= zr_2 + (_fxthetaterm_T_6 ? 16'hFCDC : 16'h324);	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:38:18, :224:19, :307:31, :309:{28,48}, :312:25
      zr_4 <= zr_3 + (_fxthetaterm_T_9 ? 16'hFE6E : 16'h192);	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:39:18, :224:19, :307:31, :309:{28,48}, :312:25
      zr_5 <= zr_4 + (_fxthetaterm_T_12 ? 16'hFF37 : 16'hC9);	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:40:18, :224:19, :307:31, :309:{28,48}, :312:25
      zr_6 <= zr_5 + (_fxthetaterm_T_15 ? 16'hFF9B : 16'h65);	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:41:18, :224:19, :307:31, :309:{28,48}, :312:25
      zr_7 <= zr_6 + (_fxthetaterm_T_18 ? 16'hFFCE : 16'h32);	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:42:18, :224:19, :307:31, :309:{28,48}, :312:25
      zr_8 <= zr_7 + (_fxthetaterm_T_21 ? 16'hFFE7 : 16'h19);	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:43:18, :224:19, :307:31, :309:{28,48}, :312:25
      zr_9 <= zr_8 + (_fxthetaterm_T_24 ? 16'hFFF3 : 16'hD);	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:44:18, :224:19, :307:31, :309:{28,48}, :312:25
      zr_10 <= zr_9 + (_fxthetaterm_T_27 ? 16'hFFFA : 16'h6);	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:45:18, :224:19, :307:31, :309:{28,48}, :312:25
      zr_11 <= zr_10 + (_fxthetaterm_T_30 ? 16'hFFFD : 16'h3);	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:46:19, :224:19, :307:31, :309:{28,48}, :312:25
      zr_12 <= zr_11 + (_fxthetaterm_T_33 ? 16'hFFFE : 16'h2);	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:47:19, :224:19, :307:31, :309:{28,48}, :312:25
      zr_13 <= zr_12 + (_fxthetaterm_T_36 ? 16'hFFFF : 16'h1);	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:48:19, :224:19, :307:31, :309:{28,48}, :312:25
      zr_14 <= zr_13;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
      zr_15 <= zr_14;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
      zr_16 <= zr_15;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
      automatic logic [31:0] _RANDOM[0:25];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
        `INIT_RANDOM_PROLOG_	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
        for (logic [4:0] i = 5'h0; i < 5'h1A; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
        end	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
        xr_0 = _RANDOM[5'h0][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_1 = _RANDOM[5'h0][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_2 = _RANDOM[5'h1][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_3 = _RANDOM[5'h1][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_4 = _RANDOM[5'h2][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_5 = _RANDOM[5'h2][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_6 = _RANDOM[5'h3][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_7 = _RANDOM[5'h3][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_8 = _RANDOM[5'h4][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_9 = _RANDOM[5'h4][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_10 = _RANDOM[5'h5][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_11 = _RANDOM[5'h5][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_12 = _RANDOM[5'h6][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_13 = _RANDOM[5'h6][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_14 = _RANDOM[5'h7][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_15 = _RANDOM[5'h7][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        xr_16 = _RANDOM[5'h8][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19
        yr_0 = _RANDOM[5'h8][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :222:19, :223:19
        yr_1 = _RANDOM[5'h9][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        yr_2 = _RANDOM[5'h9][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        yr_3 = _RANDOM[5'hA][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        yr_4 = _RANDOM[5'hA][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        yr_5 = _RANDOM[5'hB][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        yr_6 = _RANDOM[5'hB][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        yr_7 = _RANDOM[5'hC][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        yr_8 = _RANDOM[5'hC][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        yr_9 = _RANDOM[5'hD][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        yr_10 = _RANDOM[5'hD][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        yr_11 = _RANDOM[5'hE][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        yr_12 = _RANDOM[5'hE][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        yr_13 = _RANDOM[5'hF][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        yr_14 = _RANDOM[5'hF][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        yr_15 = _RANDOM[5'h10][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        yr_16 = _RANDOM[5'h10][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :223:19
        zr_0 = _RANDOM[5'h11][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_1 = _RANDOM[5'h11][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_2 = _RANDOM[5'h12][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_3 = _RANDOM[5'h12][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_4 = _RANDOM[5'h13][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_5 = _RANDOM[5'h13][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_6 = _RANDOM[5'h14][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_7 = _RANDOM[5'h14][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_8 = _RANDOM[5'h15][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_9 = _RANDOM[5'h15][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_10 = _RANDOM[5'h16][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_11 = _RANDOM[5'h16][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_12 = _RANDOM[5'h17][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_13 = _RANDOM[5'h17][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_14 = _RANDOM[5'h18][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_15 = _RANDOM[5'h18][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
        zr_16 = _RANDOM[5'h19][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7, :224:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
      `FIRRTL_AFTER_INITIAL	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:12:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FloatToFixed16 tofixedx0 (	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:227:27
    .io_in  (16'h3C00),	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :227:27
    .io_out (_tofixedx0_io_out)
  );
  FloatToFixed16 tofixedy0 (	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:228:27
    .io_in  (io_in_y0),
    .io_out (_tofixedy0_io_out)
  );
  FloatToFixed16 tofixedz0 (	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:229:27
    .io_in  (16'h0),	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:26:14, :229:27
    .io_out (_tofixedz0_io_out)
  );
  FixedToFloat tofloatxout (	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:318:29
    .io_in  (xr_16),	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:222:19
    .io_out (/* unused */)
  );
  FixedToFloat tofloatyout (	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:319:29
    .io_in  (yr_16),	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:223:19
    .io_out (/* unused */)
  );
  FixedToFloat tofloatzout (	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:320:29
    .io_in  (zr_16),	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\VCORDIC.scala:224:19
    .io_out (io_out_z)
  );
endmodule

module Atan_n16_pd16_bw16(	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
  input         clock,	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
                reset,	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
  input  [15:0] io_in,	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:14:14
  output [15:0] io_out,	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:14:14
  input         io_ready,	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:14:14
  output        io_valid	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:14:14
);

  wire [15:0] inputmag = {1'h0, io_in[14:0]};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:37:{24,32}
  reg  [15:0] shift_reg_0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_1;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_2;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_3;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_4;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_5;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_6;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_7;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_8;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_9;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_10;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_11;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_12;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_13;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_14;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_15;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  reg  [15:0] shift_reg_16;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
  always @(posedge clock) begin	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
    if (reset) begin	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
      shift_reg_0 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_1 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_2 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_3 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_4 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_5 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_6 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_7 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_8 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_9 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_10 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_11 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_12 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_13 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_14 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_15 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
      shift_reg_16 <= 16'h0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:{28,50}
    end
    else begin	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
      shift_reg_0 <= {15'h0, io_ready};	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28, :102:16
      shift_reg_1 <= shift_reg_0;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
      shift_reg_2 <= shift_reg_1;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
      shift_reg_3 <= shift_reg_2;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
      shift_reg_4 <= shift_reg_3;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
      shift_reg_5 <= shift_reg_4;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
      shift_reg_6 <= shift_reg_5;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
      shift_reg_7 <= shift_reg_6;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
      shift_reg_8 <= shift_reg_7;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
      shift_reg_9 <= shift_reg_8;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
      shift_reg_10 <= shift_reg_9;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
      shift_reg_11 <= shift_reg_10;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
      shift_reg_12 <= shift_reg_11;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
      shift_reg_13 <= shift_reg_12;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
      shift_reg_14 <= shift_reg_13;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
      shift_reg_15 <= shift_reg_14;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
      shift_reg_16 <= shift_reg_15;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:101:28
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
      automatic logic [31:0] _RANDOM[0:8];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
        `INIT_RANDOM_PROLOG_	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
        for (logic [3:0] i = 4'h0; i < 4'h9; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
        end	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
        shift_reg_0 = _RANDOM[4'h0][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_1 = _RANDOM[4'h0][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_2 = _RANDOM[4'h1][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_3 = _RANDOM[4'h1][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_4 = _RANDOM[4'h2][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_5 = _RANDOM[4'h2][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_6 = _RANDOM[4'h3][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_7 = _RANDOM[4'h3][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_8 = _RANDOM[4'h4][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_9 = _RANDOM[4'h4][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_10 = _RANDOM[4'h5][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_11 = _RANDOM[4'h5][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_12 = _RANDOM[4'h6][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_13 = _RANDOM[4'h6][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_14 = _RANDOM[4'h7][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_15 = _RANDOM[4'h7][31:16];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
        shift_reg_16 = _RANDOM[4'h8][15:0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
      `FIRRTL_AFTER_INITIAL	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  VCORDIC vcordic (	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:38:25
    .clock    (clock),
    .reset    (reset),
    .io_in_y0
      ($signed(inputmag) > 16'sh70E2
         ? {io_in[15], 15'h70E2}
         : $signed(inputmag) < 16'shA9 ? {io_in[15], 15'hA8} : io_in),	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:36:26, :37:24, :40:{28,45,73}, :41:{10,27,56}
    .io_out_z (io_out)
  );
  assign io_valid = shift_reg_16[0];	// C:\\Trig-Design-with-Chisel-HCL\\src\\main\\scala\\Atan.scala:12:7, :101:28, :106:12
endmodule

