// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module FloatToFixed16(	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:20:7
  input  [15:0] io_in,	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:23:14
  output [15:0] io_out	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:23:14
);

  wire [4:0]  _shiftamt_T = io_in[14:10] - 5'hF;	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:34:25, :36:23
  wire [18:0] _data_T_9 = {7'h1, io_in[9:0], 2'h0} >> 5'h0 - _shiftamt_T;	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:33:{39,47}, :36:23, :39:{36,44,48}
  wire [49:0] _data_T_14 = {38'h1, io_in[9:0], 2'h0} << _shiftamt_T;	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:33:47, :36:23, :39:36, :40:44
  wire [15:0] data = _shiftamt_T[4] ? _data_T_9[15:0] : _data_T_14[15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:36:23, :38:{17,26}, :39:44, :40:44
  assign io_out = io_in[15] ? 16'h0 - data : data;	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:20:7, :35:26, :38:17, :39:48, :41:{16,40}
endmodule

module CLZ16(	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:125:7
  input  [15:0] io_in,	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:126:14
  output [4:0]  io_out	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:126:14
);

  wire [6:0] bx = (|(io_in[15:8])) ? io_in[15:9] : io_in[7:1];	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:126:14, :134:{15,20,33,45}
  wire [2:0] cx = (|(bx[6:3])) ? bx[6:4] : bx[2:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:134:15, :135:{15,20,33,45}
  assign io_out =
    io_in == 16'h0
      ? 5'h10
      : {1'h0,
         ~(|(io_in[15:8])),
         ~(|(bx[6:3])),
         ~(|(cx[2:1])),
         ~((|(cx[2:1])) ? cx[2] : cx[0])};	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:125:7, :134:{15,20,33}, :135:{15,20,33}, :136:{15,20,33,45}, :139:{33,63,93}, :140:23, :142:{16,23}
endmodule

module FixedToFloat16(	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:242:7
  input  [15:0] io_in,	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:244:14
  output [15:0] io_out	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:244:14
);

  wire [4:0]      _clz16_io_out;	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:257:21
  wire [15:0]     data = io_in[15] ? ~io_in + 16'h1 : io_in;	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:254:{14,20,35,50}
  wire [524302:0] _frac_T_3 =
    {{524287{data[15]}}, data} << {15'h0, _clz16_io_out[3:0]} + 19'h1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:254:14, :257:21, :260:{32,47}, :263:{26,43}
  CLZ16 clz16 (	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:257:21
    .io_in  (data),	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:254:14
    .io_out (_clz16_io_out)
  );
  assign io_out = {io_in[15], 5'h3 - {1'h0, _clz16_io_out[3:0]} + 5'hF, _frac_T_3[15:6]};	// C:\\exp_chisel\\exp\\src\\main\\scala\\FixedPoint.scala:242:7, :254:20, :257:21, :260:47, :262:{23,46}, :263:{8,26}, :265:37
endmodule

module VCORDIC(	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
  input         clock,	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
                reset,	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
  input  [15:0] io_in_y0,	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14
  output [15:0] io_out_z	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14
);

  wire [15:0] _tofixedz0_io_out;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:273:27
  wire [15:0] _tofixedy0_io_out;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:272:27
  wire [15:0] _tofixedx0_io_out;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:271:27
  reg  [15:0] xr_0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [15:0] xr_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [15:0] xr_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [15:0] xr_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [15:0] xr_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [15:0] xr_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [15:0] xr_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [15:0] xr_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [15:0] xr_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
  reg  [15:0] yr_0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [15:0] yr_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [15:0] yr_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [15:0] yr_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [15:0] yr_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [15:0] yr_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [15:0] yr_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [15:0] yr_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [15:0] yr_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
  reg  [15:0] zr_0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [15:0] zr_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [15:0] zr_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [15:0] zr_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [15:0] zr_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [15:0] zr_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [15:0] zr_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [15:0] zr_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  reg  [15:0] zr_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
  always @(posedge clock) begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
    if (reset) begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
      xr_0 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27
      xr_1 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27
      xr_2 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27
      xr_3 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27
      xr_4 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27
      xr_5 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27
      xr_6 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27
      xr_7 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27
      xr_8 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27
      yr_0 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27
      yr_1 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27
      yr_2 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27
      yr_3 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27
      yr_4 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27
      yr_5 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27
      yr_6 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27
      yr_7 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27
      yr_8 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27
      zr_0 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :273:27
      zr_1 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :273:27
      zr_2 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :273:27
      zr_3 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :273:27
      zr_4 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :273:27
      zr_5 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :273:27
      zr_6 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :273:27
      zr_7 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :273:27
      zr_8 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :267:19, :273:27
    end
    else begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
      automatic logic        cond;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:539:31
      automatic logic [15:0] _x_1_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:545:32
      automatic logic [15:0] _y_1_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:546:32
      automatic logic        cond_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:550:31
      automatic logic [15:0] _xterm_T_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :551:33
      automatic logic [14:0] xterm_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:551:26
      automatic logic [15:0] _yterm_T_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :552:33
      automatic logic [14:0] yterm_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:552:26
      automatic logic        cond_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:539:31
      automatic logic [15:0] _xterm_T_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33
      automatic logic [13:0] xterm_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:26
      automatic logic [15:0] _yterm_T_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :542:33
      automatic logic [13:0] yterm_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:542:26
      automatic logic [15:0] _x_3_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:85:19, :545:{32,41}
      automatic logic [15:0] _y_3_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:85:19, :546:{32,41}
      automatic logic        cond_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:550:31
      automatic logic [15:0] _xterm_T_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :551:33
      automatic logic [12:0] xterm_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:551:26
      automatic logic [15:0] _yterm_T_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :552:33
      automatic logic [12:0] yterm_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:552:26
      automatic logic        cond_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:539:31
      automatic logic [15:0] _xterm_T_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33
      automatic logic [11:0] xterm_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:26
      automatic logic [15:0] _yterm_T_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :542:33
      automatic logic [11:0] yterm_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:542:26
      automatic logic [15:0] _x_5_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :545:{32,41}
      automatic logic [15:0] _y_5_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :546:{32,41}
      automatic logic        cond_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:550:31
      automatic logic [15:0] _xterm_T_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :551:33
      automatic logic [10:0] xterm_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:551:26
      automatic logic [15:0] _yterm_T_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :552:33
      automatic logic [10:0] yterm_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:552:26
      automatic logic        cond_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:539:31
      automatic logic [15:0] _xterm_T_18;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33
      automatic logic [9:0]  xterm_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:26
      automatic logic [15:0] _yterm_T_18;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :542:33
      automatic logic [9:0]  yterm_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:542:26
      automatic logic [15:0] _x_7_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :545:{32,41}
      automatic logic [15:0] _y_7_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :546:{32,41}
      automatic logic        cond_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:550:31
      automatic logic [15:0] _xterm_T_21;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :551:33
      automatic logic [8:0]  xterm_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:551:26
      automatic logic [15:0] _yterm_T_21;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :552:33
      automatic logic [8:0]  yterm_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:552:26
      automatic logic        cond_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:539:31
      automatic logic [15:0] _xterm_T_24;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33
      automatic logic [7:0]  xterm_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:26
      automatic logic [15:0] _yterm_T_24;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :542:33
      automatic logic [7:0]  yterm_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:542:26
      automatic logic [15:0] _x_9_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :545:{32,41}
      automatic logic [15:0] _y_9_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :546:{32,41}
      automatic logic        cond_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:550:31
      automatic logic [15:0] _xterm_T_27;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :551:33
      automatic logic [6:0]  xterm_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:551:26
      automatic logic [15:0] _yterm_T_27;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :552:33
      automatic logic [6:0]  yterm_9;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:552:26
      automatic logic        cond_10;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:539:31
      automatic logic [15:0] _xterm_T_30;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33
      automatic logic [5:0]  xterm_10;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:26
      automatic logic [15:0] _yterm_T_30;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :542:33
      automatic logic [5:0]  yterm_10;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:542:26
      automatic logic [15:0] _x_11_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:545:{32,41}
      automatic logic [15:0] _y_11_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:545:41, :546:{32,41}
      automatic logic        cond_11;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:550:31
      automatic logic [15:0] _xterm_T_33;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :551:33
      automatic logic [4:0]  xterm_11;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:551:26
      automatic logic [15:0] _yterm_T_33;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :552:33
      automatic logic [4:0]  yterm_11;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:552:26
      automatic logic        cond_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:539:31
      automatic logic [15:0] _xterm_T_36;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33
      automatic logic [3:0]  xterm_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:26
      automatic logic [15:0] _yterm_T_36;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :542:33
      automatic logic [3:0]  yterm_12;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:542:26
      automatic logic [15:0] _x_13_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:545:{32,41}
      automatic logic [15:0] _y_13_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:545:41, :546:{32,41}
      automatic logic        cond_13;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:550:31
      automatic logic [15:0] _xterm_T_39;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :551:33
      automatic logic [2:0]  xterm_13;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:551:26
      automatic logic [15:0] _yterm_T_39;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :552:33
      automatic logic [2:0]  yterm_13;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:552:26
      automatic logic        cond_14;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:539:31
      automatic logic [15:0] _xterm_T_42;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33
      automatic logic [1:0]  xterm_14;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:26
      automatic logic [15:0] _yterm_T_42;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :542:33
      automatic logic [1:0]  yterm_14;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:542:26
      automatic logic [15:0] _x_15_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:545:{32,41}
      automatic logic [15:0] _y_15_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:545:41, :546:{32,41}
      automatic logic        cond_15;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:550:31
      automatic logic [15:0] _yterm_T_45;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :552:33
      automatic logic [15:0] _xterm_T_45;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :551:33
      cond = $signed(yr_0) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27, :539:31
      _x_1_T_1 = xr_0 + (cond ? 16'h0 - yr_0 : yr_0);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :266:19, :273:27, :539:31, :541:33, :542:{26,33}, :545:32
      _y_1_T_1 = yr_0 - (cond ? 16'h0 - xr_0 : xr_0);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :266:19, :273:27, :539:31, :541:{26,33}, :546:32
      cond_1 = $signed(_y_1_T_1) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :273:27, :546:32, :550:31
      _xterm_T_3 = 16'h0 - _x_1_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :273:27, :541:33, :545:32, :551:33
      xterm_1 = cond_1 ? _xterm_T_3[15:1] : _x_1_T_1[15:1];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :545:32, :550:31, :551:{26,33}
      _yterm_T_3 = 16'h0 - _y_1_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :273:27, :541:33, :546:32, :552:33
      yterm_1 = cond_1 ? _yterm_T_3[15:1] : _y_1_T_1[15:1];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :546:32, :550:31, :552:{26,33}
      cond_2 = $signed(yr_1) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27, :539:31
      _xterm_T_6 = 16'h0 - xr_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27, :541:33
      xterm_2 = cond_2 ? _xterm_T_6[15:2] : xr_1[15:2];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :539:31, :541:{26,33}
      _yterm_T_6 = 16'h0 - yr_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27, :541:33, :542:33
      yterm_2 = cond_2 ? _yterm_T_6[15:2] : yr_1[15:2];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :539:31, :541:33, :542:{26,33}
      _x_3_T_1 = {{2{yterm_2[13]}}, yterm_2} + xr_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:85:19, :265:19, :542:26, :545:{32,41}
      _y_3_T_1 = yr_1 - {{2{xterm_2[13]}}, xterm_2};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:85:19, :266:19, :541:26, :546:{32,41}
      cond_3 = $signed(_y_3_T_1) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :85:19, :273:27, :546:{32,41}, :550:31
      _xterm_T_9 = 16'h0 - _x_3_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :85:19, :273:27, :541:33, :545:{32,41}, :551:33
      xterm_3 = cond_3 ? _xterm_T_9[15:3] : _x_3_T_1[15:3];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:85:19, :541:33, :545:{32,41}, :550:31, :551:{26,33}
      _yterm_T_9 = 16'h0 - _y_3_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :85:19, :273:27, :541:33, :546:{32,41}, :552:33
      yterm_3 = cond_3 ? _yterm_T_9[15:3] : _y_3_T_1[15:3];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:85:19, :541:33, :546:{32,41}, :550:31, :552:{26,33}
      cond_4 = $signed(yr_2) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27, :539:31
      _xterm_T_12 = 16'h0 - xr_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27, :541:33
      xterm_4 = cond_4 ? _xterm_T_12[15:4] : xr_2[15:4];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :539:31, :541:{26,33}
      _yterm_T_12 = 16'h0 - yr_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27, :541:33, :542:33
      yterm_4 = cond_4 ? _yterm_T_12[15:4] : yr_2[15:4];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :539:31, :541:33, :542:{26,33}
      _x_5_T_1 = {{4{yterm_4[11]}}, yterm_4} + xr_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :265:19, :542:26, :545:{32,41}
      _y_5_T_1 = yr_2 - {{4{xterm_4[11]}}, xterm_4};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :266:19, :541:26, :546:{32,41}
      cond_5 = $signed(_y_5_T_1) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :119:17, :273:27, :546:{32,41}, :550:31
      _xterm_T_15 = 16'h0 - _x_5_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :119:17, :273:27, :541:33, :545:{32,41}, :551:33
      xterm_5 = cond_5 ? _xterm_T_15[15:5] : _x_5_T_1[15:5];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :541:33, :545:{32,41}, :550:31, :551:{26,33}
      _yterm_T_15 = 16'h0 - _y_5_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :119:17, :273:27, :541:33, :546:{32,41}, :552:33
      yterm_5 = cond_5 ? _yterm_T_15[15:5] : _y_5_T_1[15:5];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :541:33, :546:{32,41}, :550:31, :552:{26,33}
      cond_6 = $signed(yr_3) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27, :539:31
      _xterm_T_18 = 16'h0 - xr_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27, :541:33
      xterm_6 = cond_6 ? _xterm_T_18[15:6] : xr_3[15:6];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :539:31, :541:{26,33}
      _yterm_T_18 = 16'h0 - yr_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27, :541:33, :542:33
      yterm_6 = cond_6 ? _yterm_T_18[15:6] : yr_3[15:6];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :539:31, :541:33, :542:{26,33}
      _x_7_T_1 = {{6{yterm_6[9]}}, yterm_6} + xr_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :265:19, :542:26, :545:{32,41}
      _y_7_T_1 = yr_3 - {{6{xterm_6[9]}}, xterm_6};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :266:19, :541:26, :546:{32,41}
      cond_7 = $signed(_y_7_T_1) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :83:18, :273:27, :546:{32,41}, :550:31
      _xterm_T_21 = 16'h0 - _x_7_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :83:18, :273:27, :541:33, :545:{32,41}, :551:33
      xterm_7 = cond_7 ? _xterm_T_21[15:7] : _x_7_T_1[15:7];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :541:33, :545:{32,41}, :550:31, :551:{26,33}
      _yterm_T_21 = 16'h0 - _y_7_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :83:18, :273:27, :541:33, :546:{32,41}, :552:33
      yterm_7 = cond_7 ? _yterm_T_21[15:7] : _y_7_T_1[15:7];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :541:33, :546:{32,41}, :550:31, :552:{26,33}
      cond_8 = $signed(yr_4) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27, :539:31
      _xterm_T_24 = 16'h0 - xr_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27, :541:33
      xterm_8 = cond_8 ? _xterm_T_24[15:8] : xr_4[15:8];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :539:31, :541:{26,33}
      _yterm_T_24 = 16'h0 - yr_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27, :541:33, :542:33
      yterm_8 = cond_8 ? _yterm_T_24[15:8] : yr_4[15:8];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :539:31, :541:33, :542:{26,33}
      _x_9_T_1 = {{8{yterm_8[7]}}, yterm_8} + xr_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :265:19, :542:26, :545:{32,41}
      _y_9_T_1 = yr_4 - {{8{xterm_8[7]}}, xterm_8};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :266:19, :541:26, :546:{32,41}
      cond_9 = $signed(_y_9_T_1) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :118:17, :273:27, :546:{32,41}, :550:31
      _xterm_T_27 = 16'h0 - _x_9_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :118:17, :273:27, :541:33, :545:{32,41}, :551:33
      xterm_9 = cond_9 ? _xterm_T_27[15:9] : _x_9_T_1[15:9];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :541:33, :545:{32,41}, :550:31, :551:{26,33}
      _yterm_T_27 = 16'h0 - _y_9_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :118:17, :273:27, :541:33, :546:{32,41}, :552:33
      yterm_9 = cond_9 ? _yterm_T_27[15:9] : _y_9_T_1[15:9];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :541:33, :546:{32,41}, :550:31, :552:{26,33}
      cond_10 = $signed(yr_5) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27, :539:31
      _xterm_T_30 = 16'h0 - xr_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27, :541:33
      xterm_10 = cond_10 ? _xterm_T_30[15:10] : xr_5[15:10];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :539:31, :541:{26,33}
      _yterm_T_30 = 16'h0 - yr_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27, :541:33, :542:33
      yterm_10 = cond_10 ? _yterm_T_30[15:10] : yr_5[15:10];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :539:31, :541:33, :542:{26,33}
      _x_11_T_1 = {{10{yterm_10[5]}}, yterm_10} + xr_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :542:26, :545:{32,41}
      _y_11_T_1 = yr_5 - {{10{xterm_10[5]}}, xterm_10};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :541:26, :545:41, :546:{32,41}
      cond_11 = $signed(_y_11_T_1) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :273:27, :545:41, :546:{32,41}, :550:31
      _xterm_T_33 = 16'h0 - _x_11_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :273:27, :541:33, :545:{32,41}, :551:33
      xterm_11 = cond_11 ? _xterm_T_33[15:11] : _x_11_T_1[15:11];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :545:{32,41}, :550:31, :551:{26,33}
      _yterm_T_33 = 16'h0 - _y_11_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :273:27, :541:33, :545:41, :546:{32,41}, :552:33
      yterm_11 = cond_11 ? _yterm_T_33[15:11] : _y_11_T_1[15:11];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :545:41, :546:{32,41}, :550:31, :552:{26,33}
      cond_12 = $signed(yr_6) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27, :539:31
      _xterm_T_36 = 16'h0 - xr_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27, :541:33
      xterm_12 = cond_12 ? _xterm_T_36[15:12] : xr_6[15:12];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :539:31, :541:{26,33}
      _yterm_T_36 = 16'h0 - yr_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27, :541:33, :542:33
      yterm_12 = cond_12 ? _yterm_T_36[15:12] : yr_6[15:12];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :539:31, :541:33, :542:{26,33}
      _x_13_T_1 = {{12{yterm_12[3]}}, yterm_12} + xr_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :542:26, :545:{32,41}
      _y_13_T_1 = yr_6 - {{12{xterm_12[3]}}, xterm_12};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :541:26, :545:41, :546:{32,41}
      cond_13 = $signed(_y_13_T_1) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :273:27, :545:41, :546:{32,41}, :550:31
      _xterm_T_39 = 16'h0 - _x_13_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :273:27, :541:33, :545:{32,41}, :551:33
      xterm_13 = cond_13 ? _xterm_T_39[15:13] : _x_13_T_1[15:13];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :545:{32,41}, :550:31, :551:{26,33}
      _yterm_T_39 = 16'h0 - _y_13_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :273:27, :541:33, :545:41, :546:{32,41}, :552:33
      yterm_13 = cond_13 ? _yterm_T_39[15:13] : _y_13_T_1[15:13];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:541:33, :545:41, :546:{32,41}, :550:31, :552:{26,33}
      cond_14 = $signed(yr_7) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27, :539:31
      _xterm_T_42 = 16'h0 - xr_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :265:19, :273:27, :541:33
      xterm_14 = cond_14 ? _xterm_T_42[15:14] : xr_7[15:14];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :539:31, :541:{26,33}
      _yterm_T_42 = 16'h0 - yr_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :266:19, :273:27, :541:33, :542:33
      yterm_14 = cond_14 ? _yterm_T_42[15:14] : yr_7[15:14];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :539:31, :541:33, :542:{26,33}
      _x_15_T_1 = {{14{yterm_14[1]}}, yterm_14} + xr_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :542:26, :545:{32,41}
      _y_15_T_1 = yr_7 - {{14{xterm_14[1]}}, xterm_14};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :541:26, :545:41, :546:{32,41}
      cond_15 = $signed(_y_15_T_1) < 16'sh0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :273:27, :545:41, :546:{32,41}, :550:31
      xr_0 <= _tofixedx0_io_out;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :271:27
      xr_1 <= {yterm_1[14], yterm_1} + _x_1_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:86:19, :265:19, :545:32, :552:26, :555:{32,41}
      xr_2 <= {{3{yterm_3[12]}}, yterm_3} + _x_3_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:84:19, :85:19, :265:19, :545:{32,41}, :552:26, :555:{32,41}
      xr_3 <= {{5{yterm_5[10]}}, yterm_5} + _x_5_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :265:19, :545:{32,41}, :552:26, :555:{32,41}
      xr_4 <= {{7{yterm_7[8]}}, yterm_7} + _x_7_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :265:19, :545:{32,41}, :552:26, :555:{32,41}
      xr_5 <= {{9{yterm_9[6]}}, yterm_9} + _x_9_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :265:19, :545:{32,41}, :552:26, :555:{32,41}
      xr_6 <= {{11{yterm_11[4]}}, yterm_11} + _x_11_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :545:{32,41}, :552:26, :555:{32,41}
      xr_7 <= {{13{yterm_13[2]}}, yterm_13} + _x_13_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:82:18, :265:19, :545:{32,41}, :552:26, :555:{32,41}
      _yterm_T_45 = 16'h0 - _y_15_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :273:27, :541:33, :545:41, :546:{32,41}, :552:33
      xr_8 <= {16{cond_15 ? _yterm_T_45[15] : _y_15_T_1[15]}} + _x_15_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19, :541:33, :545:{32,41}, :546:{32,41}, :550:31, :552:{26,33}, :555:{32,41}
      yr_0 <= _tofixedy0_io_out;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :272:27
      yr_1 <= _y_1_T_1 - {xterm_1[14], xterm_1};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:86:19, :266:19, :546:32, :551:26, :556:{32,41}
      yr_2 <= _y_3_T_1 - {{3{xterm_3[12]}}, xterm_3};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:84:19, :85:19, :266:19, :546:{32,41}, :551:26, :556:{32,41}
      yr_3 <= _y_5_T_1 - {{5{xterm_5[10]}}, xterm_5};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:119:17, :266:19, :546:{32,41}, :551:26, :555:41, :556:{32,41}
      yr_4 <= _y_7_T_1 - {{7{xterm_7[8]}}, xterm_7};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:83:18, :266:19, :546:{32,41}, :551:26, :555:41, :556:{32,41}
      yr_5 <= _y_9_T_1 - {{9{xterm_9[6]}}, xterm_9};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:118:17, :266:19, :546:{32,41}, :551:26, :555:41, :556:{32,41}
      yr_6 <= _y_11_T_1 - {{11{xterm_11[4]}}, xterm_11};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :545:41, :546:{32,41}, :551:26, :555:41, :556:{32,41}
      yr_7 <= _y_13_T_1 - {{13{xterm_13[2]}}, xterm_13};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:82:18, :266:19, :545:41, :546:{32,41}, :551:26, :556:{32,41}
      _xterm_T_45 = 16'h0 - _x_15_T_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :273:27, :541:33, :545:{32,41}, :551:33
      yr_8 <= _y_15_T_1 - {16{cond_15 ? _xterm_T_45[15] : _x_15_T_1[15]}};	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19, :541:33, :545:{32,41}, :546:{32,41}, :550:31, :551:{26,33}, :555:41, :556:{32,41}
      zr_0 <= _tofixedz0_io_out;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19, :273:27
      zr_1 <= zr_0 + (cond ? 16'hF36F : 16'hC91) + (cond_1 ? 16'hF9B8 : 16'h648);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:74:18, :75:18, :267:19, :539:31, :543:{26,33}, :550:31, :553:{26,33}, :557:32
      zr_2 <= zr_1 + (cond_2 ? 16'hFCDC : 16'h324) + (cond_3 ? 16'hFE6E : 16'h192);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:76:18, :77:18, :267:19, :539:31, :543:{26,33}, :550:31, :553:{26,33}, :557:32
      zr_3 <= zr_2 + (cond_4 ? 16'hFF37 : 16'hC9) + (cond_5 ? 16'hFF9B : 16'h65);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:78:18, :79:18, :267:19, :539:31, :543:{26,33}, :550:31, :553:{26,33}, :557:32
      zr_4 <= zr_3 + (cond_6 ? 16'hFFCE : 16'h32) + (cond_7 ? 16'hFFE7 : 16'h19);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:80:18, :81:18, :267:19, :539:31, :543:{26,33}, :550:31, :553:{26,33}, :557:32
      zr_5 <= zr_4 + (cond_8 ? 16'hFFF3 : 16'hD) + (cond_9 ? 16'hFFFA : 16'h6);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:82:18, :83:18, :267:19, :539:31, :543:{26,33}, :550:31, :553:{26,33}, :557:32
      zr_6 <= zr_5 + (cond_10 ? 16'hFFFD : 16'h3) + (cond_11 ? 16'hFFFE : 16'h2);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:84:19, :85:19, :267:19, :539:31, :543:{26,33}, :550:31, :553:{26,33}, :557:32
      zr_7 <= zr_6 + (cond_12 ? 16'hFFFF : 16'h1);	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:86:19, :267:19, :539:31, :543:{26,33}, :547:32
      zr_8 <= zr_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
      `FIRRTL_BEFORE_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
      automatic logic [31:0] _RANDOM[0:21];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
        `INIT_RANDOM_PROLOG_	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
        for (logic [4:0] i = 5'h0; i < 5'h16; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
        end	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
        xr_0 = _RANDOM[5'h0][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_1 = _RANDOM[5'h0][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_2 = _RANDOM[5'h1][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_3 = _RANDOM[5'h1][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_4 = _RANDOM[5'h2][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_5 = _RANDOM[5'h2][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_6 = _RANDOM[5'h3][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_7 = _RANDOM[5'h3][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        xr_8 = _RANDOM[5'h4][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :265:19
        yr_0 = _RANDOM[5'h8][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_1 = _RANDOM[5'h9][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_2 = _RANDOM[5'h9][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_3 = _RANDOM[5'hA][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_4 = _RANDOM[5'hA][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_5 = _RANDOM[5'hB][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_6 = _RANDOM[5'hB][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_7 = _RANDOM[5'hC][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        yr_8 = _RANDOM[5'hC][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :266:19
        zr_0 = _RANDOM[5'h11][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_1 = _RANDOM[5'h11][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_2 = _RANDOM[5'h12][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_3 = _RANDOM[5'h12][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_4 = _RANDOM[5'h13][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_5 = _RANDOM[5'h13][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_6 = _RANDOM[5'h14][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_7 = _RANDOM[5'h14][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
        zr_8 = _RANDOM[5'h15][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7, :267:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
      `FIRRTL_AFTER_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:12:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FloatToFixed16 tofixedx0 (	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:271:27
    .io_in  (16'h3C00),	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :271:27
    .io_out (_tofixedx0_io_out)
  );
  FloatToFixed16 tofixedy0 (	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:272:27
    .io_in  (io_in_y0),
    .io_out (_tofixedy0_io_out)
  );
  FloatToFixed16 tofixedz0 (	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:273:27
    .io_in  (16'h0),	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:26:14, :273:27
    .io_out (_tofixedz0_io_out)
  );
  FixedToFloat16 tofloatxout (	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:568:29
    .io_in  (xr_8),	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:265:19
    .io_out (/* unused */)
  );
  FixedToFloat16 tofloatyout (	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:569:29
    .io_in  (yr_8),	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:266:19
    .io_out (/* unused */)
  );
  FixedToFloat16 tofloatzout (	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:570:29
    .io_in  (zr_8),	// C:\\exp_chisel\\exp\\src\\main\\scala\\VCORDIC.scala:267:19
    .io_out (io_out_z)
  );
endmodule

module Atan_n16_pd8_bw16(	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
  input         clock,	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
                reset,	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
  input  [15:0] io_in,	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:14:14
  output [15:0] io_out,	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:14:14
  input         io_ready,	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:14:14
  output        io_valid	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:14:14
);

  wire [15:0] inputmag = {1'h0, io_in[14:0]};	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:36:{24,32}
  reg  [15:0] shift_reg_0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [15:0] shift_reg_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [15:0] shift_reg_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [15:0] shift_reg_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [15:0] shift_reg_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [15:0] shift_reg_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [15:0] shift_reg_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [15:0] shift_reg_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  reg  [15:0] shift_reg_8;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
  always @(posedge clock) begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
    if (reset) begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
      shift_reg_0 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_1 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_2 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_3 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_4 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_5 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_6 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_7 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
      shift_reg_8 <= 16'h0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:{26,48}
    end
    else begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
      shift_reg_0 <= {15'h0, io_ready};	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26, :135:16
      shift_reg_1 <= shift_reg_0;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_2 <= shift_reg_1;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_3 <= shift_reg_2;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_4 <= shift_reg_3;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_5 <= shift_reg_4;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_6 <= shift_reg_5;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_7 <= shift_reg_6;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
      shift_reg_8 <= shift_reg_7;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:134:26
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
      `FIRRTL_BEFORE_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
      automatic logic [31:0] _RANDOM[0:4];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
        `INIT_RANDOM_PROLOG_	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
        end	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
        shift_reg_0 = _RANDOM[3'h0][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_1 = _RANDOM[3'h0][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_2 = _RANDOM[3'h1][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_3 = _RANDOM[3'h1][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_4 = _RANDOM[3'h2][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_5 = _RANDOM[3'h2][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_6 = _RANDOM[3'h3][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_7 = _RANDOM[3'h3][31:16];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
        shift_reg_8 = _RANDOM[3'h4][15:0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
      `FIRRTL_AFTER_INITIAL	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  VCORDIC vcordic (	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:37:25
    .clock    (clock),
    .reset    (reset),
    .io_in_y0
      ($signed(inputmag) > 16'sh70E2
         ? {io_in[15], 15'h70E2}
         : $signed(inputmag) < 16'shA9 ? {io_in[15], 15'hA8} : io_in),	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:35:26, :36:24, :39:{28,45,73}, :40:{10,27,56}
    .io_out_z (io_out)
  );
  assign io_valid = shift_reg_8[0];	// C:\\exp_chisel\\exp\\src\\main\\scala\\Atan.scala:12:7, :134:26, :139:12
endmodule

